"""Unit tests for the R1.5 action-value training pipeline."""

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

# Add scripts to path so we can import the trainer
sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "scripts" / "internal"))

from train_action_value import (
    _build_feature_matrix,
    build_artifact,
    load_dataset,
    split_by_deal,
    train_family_model,
    train_pass_model,
    validate_gate_x2,
)

from bid_euchre.strategy.bidding import (
    ACTION_FEATURE_NAMES,
    STATE_FEATURE_NAMES,
)

# ── Fixtures ──────────────────────────────────────────────────


@pytest.fixture
def smoke_parquet_path():
    """Path to the SMOKE dataset (generated by Step 1)."""
    path = Path("data/runs/action_value_smoke_42/datasets/action_value.parquet")
    if not path.exists():
        pytest.skip(
            "SMOKE dataset not available (run generate_action_value_dataset.py first)"
        )
    return str(path)


@pytest.fixture
def smoke_df(smoke_parquet_path):
    """Load the SMOKE dataset."""
    return load_dataset(smoke_parquet_path)


@pytest.fixture
def split_dfs(smoke_df):
    """Train/val/test split of the SMOKE dataset."""
    return split_by_deal(smoke_df, seed=42)


@pytest.fixture
def trained_models(split_dfs):
    """Train all 4 models on the SMOKE dataset."""
    train_df, val_df, test_df = split_dfs
    models = {}
    for family in ("suit", "high", "low"):
        models[family] = train_family_model(train_df, val_df, family)
    models["pass"] = train_pass_model(train_df, val_df)
    return models


@pytest.fixture
def artifact(trained_models):
    """Build a complete artifact from trained models."""
    return build_artifact(
        trained_models,
        seed=42,
        n_deals=500,
        continuation_artifact="data/artifacts/arc_d/r0/hybrid_r0_full.json",
    )


# ── Loading ───────────────────────────────────────────────────


class TestLoadDataset:
    def test_loads_parquet(self, smoke_parquet_path):
        df = load_dataset(smoke_parquet_path)
        assert len(df) > 0
        assert "net_points" in df.columns

    def test_has_required_columns(self, smoke_df):
        for col in STATE_FEATURE_NAMES:
            assert col in smoke_df.columns, f"Missing: {col}"
        assert "net_points" in smoke_df.columns
        assert "deal_id" in smoke_df.columns
        assert "action_type" in smoke_df.columns
        assert "contract_family" in smoke_df.columns

    def test_rejects_missing_columns(self, tmp_path):
        """A parquet missing required columns should raise."""
        bad_df = pd.DataFrame({"x": [1, 2, 3]})
        path = tmp_path / "bad.parquet"
        bad_df.to_parquet(path, index=False)
        with pytest.raises(ValueError, match="missing columns"):
            load_dataset(str(path))


# ── Splitting ─────────────────────────────────────────────────


class TestSplitByDeal:
    def test_three_way_sizes(self, smoke_df):
        train, val, test = split_by_deal(smoke_df, seed=42)
        total = len(train) + len(val) + len(test)
        assert total == len(smoke_df)
        # Rough proportions (80/10/10 by deal, row counts vary)
        assert len(train) > len(val)
        assert len(train) > len(test)

    def test_no_deal_leakage(self, smoke_df):
        """No deal_id should appear in more than one split."""
        train, val, test = split_by_deal(smoke_df, seed=42)
        train_deals = set(train["deal_id"].unique())
        val_deals = set(val["deal_id"].unique())
        test_deals = set(test["deal_id"].unique())

        assert train_deals.isdisjoint(val_deals), "Train/val deal overlap"
        assert train_deals.isdisjoint(test_deals), "Train/test deal overlap"
        assert val_deals.isdisjoint(test_deals), "Val/test deal overlap"

    def test_deterministic(self, smoke_df):
        """Same seed → same split."""
        t1, v1, te1 = split_by_deal(smoke_df, seed=99)
        t2, v2, te2 = split_by_deal(smoke_df, seed=99)
        pd.testing.assert_frame_equal(
            t1.reset_index(drop=True), t2.reset_index(drop=True)
        )

    def test_different_seeds_differ(self, smoke_df):
        """Different seeds → different splits."""
        t1, _, _ = split_by_deal(smoke_df, seed=99)
        t2, _, _ = split_by_deal(smoke_df, seed=100)
        assert set(t1["deal_id"].unique()) != set(t2["deal_id"].unique())


# ── Feature Matrix ────────────────────────────────────────────


class TestBuildFeatureMatrix:
    def test_state_features_shape(self, smoke_df):
        sub = smoke_df.head(10)
        X = _build_feature_matrix(sub, STATE_FEATURE_NAMES)
        assert X.shape == (10, 52)

    def test_bid_features_shape(self, smoke_df):
        sub = smoke_df[smoke_df["action_type"] == "bid"].head(10)
        feature_names = STATE_FEATURE_NAMES + ACTION_FEATURE_NAMES
        X = _build_feature_matrix(sub, feature_names)
        assert X.shape == (10, 54)

    def test_bid_n_sq_computed(self, smoke_df):
        """bid_n_sq should be the square of bid_n."""
        sub = smoke_df[smoke_df["action_type"] == "bid"].head(10)
        feature_names = STATE_FEATURE_NAMES + ACTION_FEATURE_NAMES
        X = _build_feature_matrix(sub, feature_names)
        bid_n_col = feature_names.index("bid_n")
        bid_n_sq_col = feature_names.index("bid_n_sq")
        np.testing.assert_array_almost_equal(X[:, bid_n_sq_col], X[:, bid_n_col] ** 2)


# ── Training ──────────────────────────────────────────────────


class TestTrainFamilyModel:
    def test_coefficients_length(self, trained_models):
        """Each bid model should have 54 coefficients."""
        for family in ("suit", "high", "low"):
            model = trained_models[family]
            assert (
                len(model["coefficients"]) == 54
            ), f"{family}: expected 54 coefficients, got {len(model['coefficients'])}"

    def test_has_intercept(self, trained_models):
        for family in ("suit", "high", "low"):
            assert "intercept" in trained_models[family]
            assert isinstance(trained_models[family]["intercept"], float)

    def test_r_squared_is_float(self, trained_models):
        for family in ("suit", "high", "low"):
            r2 = trained_models[family]["r_squared"]
            assert isinstance(r2, float)

    def test_feature_names(self, trained_models):
        expected = STATE_FEATURE_NAMES + ACTION_FEATURE_NAMES
        for family in ("suit", "high", "low"):
            assert trained_models[family]["feature_names"] == expected

    def test_n_train_positive(self, trained_models):
        for family in ("suit", "high", "low"):
            assert trained_models[family]["n_train"] > 0


class TestTrainPassModel:
    def test_coefficients_length(self, trained_models):
        """Pass model should have 52 coefficients (state only)."""
        assert len(trained_models["pass"]["coefficients"]) == 52

    def test_feature_names(self, trained_models):
        assert trained_models["pass"]["feature_names"] == list(STATE_FEATURE_NAMES)

    def test_r_squared_is_float(self, trained_models):
        assert isinstance(trained_models["pass"]["r_squared"], float)


# ── Artifact ──────────────────────────────────────────────────


class TestBuildArtifact:
    def test_schema_version(self, artifact):
        assert artifact["schema_version"] == "action_value_olsa_v1"

    def test_has_all_models(self, artifact):
        assert set(artifact["models"].keys()) == {"suit", "high", "low", "pass"}

    def test_target_is_net_points(self, artifact):
        assert artifact["target"] == "net_points"

    def test_risk_mode_neutral(self, artifact):
        assert artifact["risk_mode"] == "neutral"

    def test_action_features(self, artifact):
        assert artifact["action_features"] == ["bid_n", "bid_n_sq"]

    def test_metadata(self, artifact):
        meta = artifact["metadata"]
        assert meta["n_deals"] == 500
        assert meta["training_seed"] == 42
        assert meta["arm"] == "full"

    def test_continuation_policy(self, artifact):
        assert artifact["continuation_policy"] == "hybrid_r0_full"


# ── Gate X2 ───────────────────────────────────────────────────


class TestGateX2:
    def test_passes_on_valid_artifact(self, artifact):
        """Should not raise on a real trained artifact."""
        validate_gate_x2(artifact)

    def test_fails_on_low_r2(self):
        """Should raise AssertionError when R² is below threshold."""
        bad_artifact = {
            "models": {
                "suit": {"r_squared": 0.001},
                "high": {"r_squared": 0.10},
                "low": {"r_squared": 0.10},
                "pass": {"r_squared": 0.10},
            }
        }
        with pytest.raises(AssertionError, match="suit"):
            validate_gate_x2(bad_artifact)


# ── Artifact Loadable ─────────────────────────────────────────


class TestArtifactLoadableByBidder:
    def test_roundtrip(self, artifact, tmp_path):
        """ActionValueBidder should be able to load the produced artifact."""
        from bid_euchre.strategy.bidding import ActionValueBidder

        artifact_path = tmp_path / "test_artifact.json"
        artifact_path.write_text(json.dumps(artifact))

        # Should not raise
        bidder = ActionValueBidder(str(artifact_path))
        assert bidder.models is not None
        assert bidder.pass_model is not None


# ── End-to-End ────────────────────────────────────────────────


class TestEndToEnd:
    def test_full_pipeline(self, smoke_parquet_path):
        """Full pipeline: load → split → train → artifact → gate."""
        df = load_dataset(smoke_parquet_path)
        train_df, val_df, test_df = split_by_deal(df, seed=42)

        models = {}
        for family in ("suit", "high", "low"):
            models[family] = train_family_model(train_df, val_df, family)
        models["pass"] = train_pass_model(train_df, val_df)

        artifact = build_artifact(
            models,
            seed=42,
            n_deals=df["deal_id"].nunique(),
            continuation_artifact="hybrid_r0_full.json",
        )

        # Should pass Gate X2
        validate_gate_x2(artifact)

        # Should be valid JSON
        json_str = json.dumps(artifact)
        reloaded = json.loads(json_str)
        assert reloaded["schema_version"] == "action_value_olsa_v1"
