"""Unit tests for the R1.5 action-value training pipeline."""

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

# Add scripts to path so we can import the trainer
sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "scripts" / "internal"))

from train_action_value import (
    _INTERACTION_FORMULAS,
    _PARTNER_FEATURE_NAMES,
    _ZERO_MASK_COLUMNS,
    FEATURE_SETS,
    INTERACTION_FEATURE_NAMES,
    METADATA_COLS,
    VALID_TARGETS,
    _artifact_filename,
    _build_feature_matrix,
    build_artifact,
    load_dataset,
    split_by_deal,
    train_family_model,
    train_pass_model,
    validate_gate_x2,
)

from bid_euchre.strategy.bidding import (
    _HAND_FEATURE_NAMES,
    _POSITIONAL_FEATURE_NAMES,
    ACTION_FEATURE_NAMES,
    STATE_FEATURE_NAMES,
    _infer_partner_features,
    _validate_artifact_features,
    _validate_pass_model_features,
    compute_interaction_features,
)
from bid_euchre.strategy.bidding import (
    INTERACTION_FEATURE_NAMES as BIDDER_INTERACTION_FEATURE_NAMES,
)

# ── Fixtures ──────────────────────────────────────────────────


@pytest.fixture
def smoke_parquet_path():
    """Path to the SMOKE dataset (generated by Step 1).

    Skips if the file is missing or stale (missing required STATE_FEATURE_NAMES
    columns), which happens when the feature schema evolves but the local
    parquet has not been regenerated.
    """
    path = Path("data/runs/action_value_smoke_42/datasets/action_value.parquet")
    if not path.exists():
        pytest.skip(
            "SMOKE dataset not available (run generate_action_value_dataset.py first)"
        )
    # Detect stale parquet: read schema only (no data) and check for missing columns
    parquet_cols = set(pd.read_parquet(path, columns=[]).columns)
    missing = set(STATE_FEATURE_NAMES) - parquet_cols
    if missing:
        pytest.skip(
            f"SMOKE dataset stale — missing {len(missing)} STATE_FEATURE_NAMES "
            f"columns (regenerate with generate_action_value_dataset.py): "
            f"{sorted(missing)[:5]}{'...' if len(missing) > 5 else ''}"
        )
    return str(path)


@pytest.fixture
def smoke_df(smoke_parquet_path):
    """Load the SMOKE dataset."""
    return load_dataset(smoke_parquet_path)


@pytest.fixture
def split_dfs(smoke_df):
    """Train/val/test split of the SMOKE dataset."""
    return split_by_deal(smoke_df, seed=42)


@pytest.fixture
def trained_models(split_dfs):
    """Train all 4 models on the SMOKE dataset."""
    train_df, val_df, test_df = split_dfs
    models = {}
    for family in ("suit", "high", "low"):
        models[family] = train_family_model(train_df, val_df, family)
    models["pass"] = train_pass_model(train_df, val_df)
    return models


@pytest.fixture
def artifact(trained_models):
    """Build a complete artifact from trained models."""
    return build_artifact(
        trained_models,
        seed=42,
        n_deals=500,
        continuation_artifact="data/artifacts/arc_d/r0/hybrid_r0_full.json",
    )


# ── Loading ───────────────────────────────────────────────────


class TestLoadDataset:
    def test_loads_parquet(self, smoke_parquet_path):
        df = load_dataset(smoke_parquet_path)
        assert len(df) > 0
        assert "net_points" in df.columns

    def test_has_required_columns(self, smoke_df):
        for col in STATE_FEATURE_NAMES:
            assert col in smoke_df.columns, f"Missing: {col}"
        assert "net_points" in smoke_df.columns
        assert "deal_id" in smoke_df.columns
        assert "action_type" in smoke_df.columns
        assert "contract_family" in smoke_df.columns

    def test_rejects_missing_columns(self, tmp_path):
        """A parquet missing required columns should raise."""
        bad_df = pd.DataFrame({"x": [1, 2, 3]})
        path = tmp_path / "bad.parquet"
        bad_df.to_parquet(path, index=False)
        with pytest.raises(ValueError, match="missing columns"):
            load_dataset(str(path))


# ── Splitting ─────────────────────────────────────────────────


class TestSplitByDeal:
    def test_three_way_sizes(self, smoke_df):
        train, val, test = split_by_deal(smoke_df, seed=42)
        total = len(train) + len(val) + len(test)
        assert total == len(smoke_df)
        # Rough proportions (80/10/10 by deal, row counts vary)
        assert len(train) > len(val)
        assert len(train) > len(test)

    def test_no_deal_leakage(self, smoke_df):
        """No deal_id should appear in more than one split."""
        train, val, test = split_by_deal(smoke_df, seed=42)
        train_deals = set(train["deal_id"].unique())
        val_deals = set(val["deal_id"].unique())
        test_deals = set(test["deal_id"].unique())

        assert train_deals.isdisjoint(val_deals), "Train/val deal overlap"
        assert train_deals.isdisjoint(test_deals), "Train/test deal overlap"
        assert val_deals.isdisjoint(test_deals), "Val/test deal overlap"

    def test_deterministic(self, smoke_df):
        """Same seed → same split."""
        t1, v1, te1 = split_by_deal(smoke_df, seed=99)
        t2, v2, te2 = split_by_deal(smoke_df, seed=99)
        pd.testing.assert_frame_equal(
            t1.reset_index(drop=True), t2.reset_index(drop=True)
        )

    def test_different_seeds_differ(self, smoke_df):
        """Different seeds → different splits."""
        t1, _, _ = split_by_deal(smoke_df, seed=99)
        t2, _, _ = split_by_deal(smoke_df, seed=100)
        assert set(t1["deal_id"].unique()) != set(t2["deal_id"].unique())


# ── Feature Matrix ────────────────────────────────────────────


class TestBuildFeatureMatrix:
    def test_state_features_shape(self, smoke_df):
        sub = smoke_df.head(10)
        X = _build_feature_matrix(sub, STATE_FEATURE_NAMES)
        assert X.shape == (10, len(STATE_FEATURE_NAMES))

    def test_bid_features_shape(self, smoke_df):
        sub = smoke_df[smoke_df["action_type"] == "bid"].head(10)
        feature_names = STATE_FEATURE_NAMES + ACTION_FEATURE_NAMES
        X = _build_feature_matrix(sub, feature_names)
        assert X.shape == (10, len(STATE_FEATURE_NAMES) + len(ACTION_FEATURE_NAMES))

    def test_bid_n_sq_computed(self, smoke_df):
        """bid_n_sq should be the square of bid_n."""
        sub = smoke_df[smoke_df["action_type"] == "bid"].head(10)
        feature_names = STATE_FEATURE_NAMES + ACTION_FEATURE_NAMES
        X = _build_feature_matrix(sub, feature_names)
        bid_n_col = feature_names.index("bid_n")
        bid_n_sq_col = feature_names.index("bid_n_sq")
        np.testing.assert_array_almost_equal(X[:, bid_n_sq_col], X[:, bid_n_col] ** 2)


# ── Training ──────────────────────────────────────────────────


class TestTrainFamilyModel:
    def test_coefficients_length(self, trained_models):
        """Each bid model should have state + action coefficients."""
        expected = len(STATE_FEATURE_NAMES) + len(ACTION_FEATURE_NAMES)
        for family in ("suit", "high", "low"):
            model = trained_models[family]
            assert (
                len(model["coefficients"]) == expected
            ), f"{family}: expected {expected} coefficients, got {len(model['coefficients'])}"

    def test_has_intercept(self, trained_models):
        for family in ("suit", "high", "low"):
            assert "intercept" in trained_models[family]
            assert isinstance(trained_models[family]["intercept"], float)

    def test_r_squared_is_float(self, trained_models):
        for family in ("suit", "high", "low"):
            r2 = trained_models[family]["r_squared"]
            assert isinstance(r2, float)

    def test_feature_names(self, trained_models):
        expected = STATE_FEATURE_NAMES + ACTION_FEATURE_NAMES
        for family in ("suit", "high", "low"):
            assert trained_models[family]["feature_names"] == expected

    def test_n_train_positive(self, trained_models):
        for family in ("suit", "high", "low"):
            assert trained_models[family]["n_train"] > 0


class TestTrainPassModel:
    def test_coefficients_length(self, trained_models):
        """Pass model should have state-only coefficients."""
        assert len(trained_models["pass"]["coefficients"]) == len(STATE_FEATURE_NAMES)

    def test_feature_names(self, trained_models):
        assert trained_models["pass"]["feature_names"] == list(STATE_FEATURE_NAMES)

    def test_r_squared_is_float(self, trained_models):
        assert isinstance(trained_models["pass"]["r_squared"], float)


# ── Artifact ──────────────────────────────────────────────────


class TestBuildArtifact:
    def test_schema_version(self, artifact):
        assert artifact["schema_version"] == "action_value_olsa_v1"

    def test_has_all_models(self, artifact):
        assert set(artifact["models"].keys()) == {"suit", "high", "low", "pass"}

    def test_target_is_net_points(self, artifact):
        assert artifact["target"] == "net_points"

    def test_risk_mode_neutral(self, artifact):
        assert artifact["risk_mode"] == "neutral"

    def test_action_features(self, artifact):
        assert artifact["action_features"] == ["bid_n", "bid_n_sq"]

    def test_metadata(self, artifact):
        meta = artifact["metadata"]
        assert meta["n_deals"] == 500
        assert meta["training_seed"] == 42
        assert meta["arm"] == "full"

    def test_continuation_policy(self, artifact):
        assert artifact["continuation_policy"] == "hybrid_r0_full"


# ── Gate X2 ───────────────────────────────────────────────────


class TestGateX2:
    def test_passes_on_valid_artifact(self, artifact):
        """Should not raise on a real trained artifact."""
        validate_gate_x2(artifact)

    def test_fails_on_low_r2(self):
        """Should raise AssertionError when R² is below threshold."""
        bad_artifact = {
            "models": {
                "suit": {"r_squared": 0.001},
                "high": {"r_squared": 0.10},
                "low": {"r_squared": 0.10},
                "pass": {"r_squared": 0.10},
            }
        }
        with pytest.raises(AssertionError, match="suit"):
            validate_gate_x2(bad_artifact)


# ── Artifact Loadable ─────────────────────────────────────────


class TestArtifactLoadableByBidder:
    def test_roundtrip(self, artifact, tmp_path):
        """ActionValueBidder should be able to load the produced artifact."""
        from bid_euchre.strategy.bidding import ActionValueBidder

        artifact_path = tmp_path / "test_artifact.json"
        artifact_path.write_text(json.dumps(artifact))

        # Should not raise
        bidder = ActionValueBidder(str(artifact_path))
        assert bidder.models is not None
        assert bidder.pass_model is not None


# ── End-to-End ────────────────────────────────────────────────


class TestEndToEnd:
    def test_full_pipeline(self, smoke_parquet_path):
        """Full pipeline: load → split → train → artifact → gate."""
        df = load_dataset(smoke_parquet_path)
        train_df, val_df, test_df = split_by_deal(df, seed=42)

        models = {}
        for family in ("suit", "high", "low"):
            models[family] = train_family_model(train_df, val_df, family)
        models["pass"] = train_pass_model(train_df, val_df)

        artifact = build_artifact(
            models,
            seed=42,
            n_deals=df["deal_id"].nunique(),
            continuation_artifact="hybrid_r0_full.json",
        )

        # Should pass Gate X2
        validate_gate_x2(artifact)

        # Should be valid JSON
        json_str = json.dumps(artifact)
        reloaded = json.loads(json_str)
        assert reloaded["schema_version"] == "action_value_olsa_v1"


# ── Feature Set Ablation ─────────────────────────────────────


class TestFeatureSets:
    def test_feature_set_r0_subset(self):
        """R0 feature set must be a proper subset of full feature set."""
        r0_set = set(FEATURE_SETS["r0"])
        full_set = set(FEATURE_SETS["full"])
        assert r0_set < full_set, "R0 features should be a proper subset of full"

    def test_feature_set_r0_length(self):
        """R0 feature set must have exactly 39 features."""
        assert len(FEATURE_SETS["r0"]) == 39

    def test_feature_set_full_length(self):
        """Full feature set must have exactly 69 features (R2)."""
        assert len(FEATURE_SETS["full"]) == 69

    def test_feature_set_r0_matches_hand_features(self):
        """R0 features are the first 39 entries of STATE_FEATURE_NAMES."""
        assert FEATURE_SETS["r0"] == list(STATE_FEATURE_NAMES[:39])

    def test_valid_targets(self):
        """VALID_TARGETS includes both supported target columns."""
        assert "net_points" in VALID_TARGETS
        assert "tricks_won" in VALID_TARGETS


# ── Artifact Metadata ────────────────────────────────────────


class TestBuildArtifactAblation:
    def test_records_feature_set_full(self):
        """Artifact records feature_set='full' by default."""
        models = _dummy_models()
        artifact = build_artifact(
            models, seed=42, n_deals=100, continuation_artifact="test.json"
        )
        assert artifact["feature_set"] == "full"

    def test_records_feature_set_r0(self):
        """Artifact records feature_set='r0' when specified."""
        models = _dummy_models()
        artifact = build_artifact(
            models,
            seed=42,
            n_deals=100,
            continuation_artifact="test.json",
            feature_set="r0",
        )
        assert artifact["feature_set"] == "r0"

    def test_records_target_net_points(self):
        """Artifact records target='net_points' by default."""
        models = _dummy_models()
        artifact = build_artifact(
            models, seed=42, n_deals=100, continuation_artifact="test.json"
        )
        assert artifact["target"] == "net_points"

    def test_records_target_tricks_won(self):
        """Artifact records target='tricks_won' when specified."""
        models = _dummy_models()
        artifact = build_artifact(
            models,
            seed=42,
            n_deals=100,
            continuation_artifact="test.json",
            target_col="tricks_won",
        )
        assert artifact["target"] == "tricks_won"


# ── Target Column Validation ─────────────────────────────────


class TestLoadDatasetTargetValidation:
    def test_missing_target_column_raises(self, tmp_path):
        """Loading with a target column not in the dataset should raise."""
        # Build a minimal valid dataframe (with all metadata + state features + net_points)
        n_rows = 5
        data = {col: range(n_rows) for col in METADATA_COLS}
        for col in STATE_FEATURE_NAMES:
            data[col] = [0.0] * n_rows
        data["net_points"] = [1.0] * n_rows
        df = pd.DataFrame(data)

        path = tmp_path / "no_tricks.parquet"
        df.to_parquet(path, index=False)

        # Should succeed with default target
        load_dataset(str(path))

        # Should fail when requesting tricks_won (not in dataset)
        with pytest.raises(ValueError, match="missing columns.*tricks_won"):
            load_dataset(str(path), target_col="tricks_won")


# ── Artifact Filename ────────────────────────────────────────


class TestArtifactFilename:
    def test_full_filename(self):
        assert _artifact_filename("full") == "action_value_full.json"

    def test_r0_filename(self):
        assert _artifact_filename("r0") == "action_value_r0_features.json"


# ── No-Partner Feature Set ───────────────────────────────────


class TestNoPartnerFeatureSet:
    def test_no_partner_has_69_features(self):
        """no-partner uses full 69 state features (zero-masked at training)."""
        assert len(FEATURE_SETS["no-partner"]) == 69

    def test_no_partner_equals_full_features(self):
        """no-partner feature list is identical to full."""
        assert FEATURE_SETS["no-partner"] == FEATURE_SETS["full"]

    def test_partner_feature_names_correct(self):
        """_PARTNER_FEATURE_NAMES matches STATE_FEATURE_NAMES positions 39-44 (v2)."""
        assert _PARTNER_FEATURE_NAMES == [
            "partner_level_same_suit",
            "partner_level_same_color",
            "partner_level_off_color",
            "partner_level_high",
            "partner_level_low",
            "partner_passed",
        ]
        for name in _PARTNER_FEATURE_NAMES:
            assert name in FEATURE_SETS["full"]

    def test_zero_mask_columns_maps_no_partner(self):
        """_ZERO_MASK_COLUMNS has 'no-partner' → partner + position + opponent feature names."""
        from train_action_value import _OPPONENT_FEATURE_NAMES, _POSITION_FEATURE_NAMES

        assert "no-partner" in _ZERO_MASK_COLUMNS
        assert _ZERO_MASK_COLUMNS["no-partner"] == (
            _PARTNER_FEATURE_NAMES + _POSITION_FEATURE_NAMES + _OPPONENT_FEATURE_NAMES
        )

    def test_zero_mask_produces_zero_coefficients(self, smoke_parquet_path):
        """Training with zeroed partner columns should produce ~0 coefficients."""
        df = load_dataset(smoke_parquet_path)
        # Zero-mask partner columns (same as --feature-set no-partner)
        for col in _PARTNER_FEATURE_NAMES:
            df[col] = 0.0

        train_df, val_df, _ = split_by_deal(df, seed=42)
        model = train_family_model(train_df, val_df, "suit")

        # Partner feature coefficients should be exactly 0 (or very close)
        feature_names = model["feature_names"]
        for pname in _PARTNER_FEATURE_NAMES:
            idx = feature_names.index(pname)
            assert (
                abs(model["coefficients"][idx]) < 1e-10
            ), f"Coefficient for {pname} should be ~0, got {model['coefficients'][idx]}"

    def test_no_partner_artifact_loadable(self, smoke_parquet_path):
        """Artifact from no-partner training loads in ActionValueBidder."""
        from bid_euchre.strategy.bidding import ActionValueBidder

        df = load_dataset(smoke_parquet_path)
        for col in _PARTNER_FEATURE_NAMES:
            df[col] = 0.0

        train_df, val_df, _ = split_by_deal(df, seed=42)
        models = {}
        for family in ("suit", "high", "low"):
            models[family] = train_family_model(train_df, val_df, family)
        models["pass"] = train_pass_model(train_df, val_df)

        artifact = build_artifact(
            models,
            seed=42,
            n_deals=df["deal_id"].nunique(),
            continuation_artifact="hybrid_r0_full.json",
            feature_set="no-partner",
        )

        # Write and load — should not raise
        import json
        import tempfile

        with tempfile.NamedTemporaryFile(suffix=".json", mode="w", delete=False) as f:
            json.dump(artifact, f)
            f.flush()
            bidder = ActionValueBidder(f.name)
            assert bidder.models is not None

    def test_artifact_filename_no_partner(self):
        """no-partner feature set produces expected filename."""
        assert (
            _artifact_filename("no-partner") == "action_value_no-partner_features.json"
        )


# ── Interaction Feature Set ───────────────────────────────────


class TestInteractionFeatureSet:
    def test_interaction_has_72_features(self):
        """interaction feature set = 69 state + 3 interaction terms."""
        assert len(FEATURE_SETS["interaction"]) == 72

    def test_interaction_starts_with_state_features(self):
        """First 69 features match STATE_FEATURE_NAMES."""
        n_state = len(STATE_FEATURE_NAMES)
        assert FEATURE_SETS["interaction"][:n_state] == list(STATE_FEATURE_NAMES)

    def test_interaction_names_match_bidder(self):
        """Training and bidder interaction feature names are identical."""
        assert INTERACTION_FEATURE_NAMES == list(BIDDER_INTERACTION_FEATURE_NAMES)

    def test_interaction_formulas_cover_all_names(self):
        """Every interaction feature name has a formula."""
        for name in INTERACTION_FEATURE_NAMES:
            assert name in _INTERACTION_FORMULAS

    def test_build_feature_matrix_computes_interactions(self, smoke_parquet_path):
        """_build_feature_matrix computes interaction terms from base columns."""
        df = load_dataset(smoke_parquet_path)
        feature_names = FEATURE_SETS["interaction"] + list(ACTION_FEATURE_NAMES)
        X = _build_feature_matrix(df.head(10), feature_names)
        # interaction features are at positions N, N+1, N+2 (before action features)
        n_state = len(STATE_FEATURE_NAMES)
        bowers = df["bowers"].values[:10]
        trump_count = df["trump_count"].values[:10]
        np.testing.assert_array_almost_equal(X[:, n_state], bowers * trump_count)
        np.testing.assert_array_almost_equal(
            X[:, n_state + 1], trump_count * trump_count
        )
        np.testing.assert_array_almost_equal(X[:, n_state + 2], bowers * bowers)

    def test_interaction_model_trains(self, smoke_parquet_path):
        """Training with interaction feature set produces valid model."""
        df = load_dataset(smoke_parquet_path)
        train_df, val_df, _ = split_by_deal(df, seed=42)
        model = train_family_model(
            train_df,
            val_df,
            "suit",
            state_feature_names=FEATURE_SETS["interaction"],
        )
        # Model should have interaction-state + action features
        expected_n = len(FEATURE_SETS["interaction"]) + len(ACTION_FEATURE_NAMES)
        assert len(model["feature_names"]) == expected_n
        assert len(model["coefficients"]) == expected_n
        assert model["r_squared"] > 0  # Sanity: non-degenerate

    def test_interaction_artifact_loadable(self, smoke_parquet_path):
        """Artifact from interaction training loads in ActionValueBidder."""
        from bid_euchre.strategy.bidding import ActionValueBidder

        df = load_dataset(smoke_parquet_path)
        train_df, val_df, _ = split_by_deal(df, seed=42)
        models = {}
        for family in ("suit", "high", "low"):
            models[family] = train_family_model(
                train_df,
                val_df,
                family,
                state_feature_names=FEATURE_SETS["interaction"],
            )
        models["pass"] = train_pass_model(
            train_df,
            val_df,
            state_feature_names=FEATURE_SETS["interaction"],
        )

        artifact = build_artifact(
            models,
            seed=42,
            n_deals=df["deal_id"].nunique(),
            continuation_artifact="hybrid_r0_full.json",
            feature_set="interaction",
        )

        import tempfile

        with tempfile.NamedTemporaryFile(suffix=".json", mode="w", delete=False) as f:
            json.dump(artifact, f)
            f.flush()
            bidder = ActionValueBidder(f.name)
            assert bidder._has_interactions is True
            assert bidder.models is not None

    def test_compute_interaction_features(self):
        """compute_interaction_features produces correct products."""
        # state[0]=bowers=2, state[1]=trump_count=5
        state = np.zeros(len(STATE_FEATURE_NAMES))
        state[0] = 2.0  # bowers
        state[1] = 5.0  # trump_count
        result = compute_interaction_features(state)
        assert len(result) == 3
        assert result[0] == 10.0  # 2 * 5
        assert result[1] == 25.0  # 5 * 5
        assert result[2] == 4.0  # 2 * 2

    def test_artifact_filename_interaction(self):
        """interaction feature set produces expected filename."""
        assert (
            _artifact_filename("interaction")
            == "action_value_interaction_features.json"
        )


# ── Helpers ──────────────────────────────────────────────────


def _dummy_models() -> dict[str, dict]:
    """Create minimal model dicts for artifact tests (no real training)."""
    n_state = len(STATE_FEATURE_NAMES)
    n_action = len(ACTION_FEATURE_NAMES)
    model = {
        "coefficients": [0.0] * (n_state + n_action),
        "intercept": 0.0,
        "feature_names": list(STATE_FEATURE_NAMES) + list(ACTION_FEATURE_NAMES),
        "r_squared": 0.5,
        "mae": 1.0,
        "n_train": 100,
        "n_val": 20,
    }
    pass_model = {
        "coefficients": [0.0] * n_state,
        "intercept": 0.0,
        "feature_names": list(STATE_FEATURE_NAMES),
        "r_squared": 0.3,
        "mae": 1.5,
        "n_train": 100,
        "n_val": 20,
    }
    return {"suit": model, "high": model, "low": model, "pass": pass_model}


# ── Provenance Metadata ─────────────────────────────────────


class TestBuildArtifactProvenance:
    def test_model_class_ols_by_default(self):
        """OLS artifact records model_class='ols'."""
        models = _dummy_models()
        artifact = build_artifact(
            models, seed=42, n_deals=100, continuation_artifact="test.json"
        )
        assert artifact["metadata"]["model_class"] == "ols"

    def test_continuation_artifact_path_recorded(self):
        """Artifact records continuation_artifact_path."""
        models = _dummy_models()
        artifact = build_artifact(
            models,
            seed=42,
            n_deals=100,
            continuation_artifact="data/artifacts/arc_d/r0/hybrid_r0_full.json",
        )
        assert (
            artifact["metadata"]["continuation_artifact_path"]
            == "data/artifacts/arc_d/r0/hybrid_r0_full.json"
        )

    def test_dataset_provenance_included(self):
        """Dataset path and SHA are recorded when provided."""
        models = _dummy_models()
        artifact = build_artifact(
            models,
            seed=42,
            n_deals=100,
            continuation_artifact="test.json",
            dataset_path="data/runs/test/action_value.parquet",
            dataset_sha256="abc123def456",
        )
        assert (
            artifact["metadata"]["dataset_path"]
            == "data/runs/test/action_value.parquet"
        )
        assert artifact["metadata"]["dataset_sha256"] == "abc123def456"

    def test_continuation_sha_included(self):
        """Continuation artifact SHA is recorded when provided."""
        models = _dummy_models()
        artifact = build_artifact(
            models,
            seed=42,
            n_deals=100,
            continuation_artifact="test.json",
            continuation_artifact_sha256="xyz789",
        )
        assert artifact["metadata"]["continuation_artifact_sha256"] == "xyz789"

    def test_provenance_fields_optional(self):
        """Provenance fields are omitted when not provided (backward compat)."""
        models = _dummy_models()
        artifact = build_artifact(
            models, seed=42, n_deals=100, continuation_artifact="test.json"
        )
        assert "dataset_path" not in artifact["metadata"]
        assert "dataset_sha256" not in artifact["metadata"]
        assert "continuation_artifact_sha256" not in artifact["metadata"]
        # But model_class and continuation_artifact_path are always present
        assert "model_class" in artifact["metadata"]
        assert "continuation_artifact_path" in artifact["metadata"]


class TestBuildGbtArtifactProvenance:
    @staticmethod
    def _build_gbt(tmp_path, **kwargs):
        """Helper: build a GBT artifact with joblib.dump patched out."""
        from unittest.mock import patch

        from train_action_value import build_gbt_artifact

        meta = {
            "feature_names": ["x"],
            "r_squared": 0.5,
            "mae": 1.0,
            "n_train": 100,
            "n_val": 20,
            "feature_importances": {"x": 1.0},
        }
        gbt_models = {"suit": "m", "high": "m", "low": "m", "pass": "m"}
        model_metadata = {"suit": meta, "high": meta, "low": meta, "pass": meta}
        with patch("joblib.dump"):
            return build_gbt_artifact(
                gbt_models,
                model_metadata,
                tmp_path,
                seed=42,
                n_deals=100,
                continuation_artifact="test.json",
                **kwargs,
            )

    def test_model_class_gbt(self, tmp_path):
        """GBT artifact records model_class='gbt'."""
        artifact = self._build_gbt(tmp_path)
        assert artifact["metadata"]["model_class"] == "gbt"
        assert artifact["metadata"]["continuation_artifact_path"] == "test.json"

    def test_gbt_provenance_fields(self, tmp_path):
        """GBT artifact includes provenance when provided."""
        artifact = self._build_gbt(
            tmp_path,
            dataset_path="data.parquet",
            dataset_sha256="abc",
            continuation_artifact_sha256="xyz",
        )
        assert artifact["metadata"]["dataset_path"] == "data.parquet"
        assert artifact["metadata"]["dataset_sha256"] == "abc"
        assert artifact["metadata"]["continuation_artifact_sha256"] == "xyz"


class TestR0HandOnlyFeatureInference:
    """Tests for R0 hand-only models with no positional or partner features."""

    def test_infer_partner_features_r0_returns_empty(self):
        """R0 hand-only feature list (no positional anchor) returns empty partner list."""
        r0_features = list(_HAND_FEATURE_NAMES)  # 39 hand features only
        result = _infer_partner_features(r0_features)
        assert result == []

    def test_infer_partner_features_full_returns_partners(self):
        """Full feature list with positional anchor returns partner features."""
        partner = ["partner_bid_level", "partner_passed", "partner_suit_match"]
        full_features = (
            list(_HAND_FEATURE_NAMES) + partner + list(_POSITIONAL_FEATURE_NAMES)
        )
        result = _infer_partner_features(full_features)
        assert result == partner

    def test_infer_partner_features_no_partner_with_positional(self):
        """Feature list with positional but no partner returns empty list."""
        features = list(_HAND_FEATURE_NAMES) + list(_POSITIONAL_FEATURE_NAMES)
        result = _infer_partner_features(features)
        assert result == []

    def test_validate_artifact_features_r0(self):
        """R0 artifact (39 hand + 2 action) validates successfully."""
        r0_model_features = list(_HAND_FEATURE_NAMES) + list(ACTION_FEATURE_NAMES)
        partner_names, has_positional = _validate_artifact_features(
            r0_model_features, has_interactions=False
        )
        assert partner_names == []
        assert has_positional is False

    def test_validate_artifact_features_full(self):
        """Full artifact (39 hand + 3 partner + 10 positional + 2 action) validates."""
        partner = ["partner_bid_level", "partner_passed", "partner_suit_match"]
        full_features = (
            list(_HAND_FEATURE_NAMES)
            + partner
            + list(_POSITIONAL_FEATURE_NAMES)
            + list(ACTION_FEATURE_NAMES)
        )
        partner_names, has_positional = _validate_artifact_features(
            full_features, has_interactions=False
        )
        assert partner_names == partner
        assert has_positional is True

    def test_validate_artifact_features_r0_wrong_features_raises(self):
        """R0 artifact with wrong hand features raises ValueError."""
        bad_features = ["wrong_feature"] + list(ACTION_FEATURE_NAMES)
        with pytest.raises(ValueError, match="structural mismatch"):
            _validate_artifact_features(bad_features, has_interactions=False)

    def test_validate_pass_model_r0(self):
        """R0 pass model (39 hand only, no action features) validates."""
        r0_pass_features = list(_HAND_FEATURE_NAMES)
        # Should not raise
        _validate_pass_model_features(
            r0_pass_features,
            partner_feature_names=[],
            has_interactions=False,
            has_positional=False,
        )

    def test_validate_pass_model_full(self):
        """Full pass model (39 hand + 3 partner + 10 positional) validates."""
        partner = ["partner_bid_level", "partner_passed", "partner_suit_match"]
        full_pass_features = (
            list(_HAND_FEATURE_NAMES) + partner + list(_POSITIONAL_FEATURE_NAMES)
        )
        _validate_pass_model_features(
            full_pass_features,
            partner_feature_names=partner,
            has_interactions=False,
            has_positional=True,
        )

    def test_validate_pass_model_r0_with_positional_accepted(self):
        """Pass model with positional features but has_positional=False validates.

        Forward selection may keep positional features (e.g. seat_rel_2) while
        dropping current_high_bid, resulting in has_positional=False. All
        positional features should be accepted in the non-positional branch.
        """
        features_with_positional = list(_HAND_FEATURE_NAMES) + list(
            _POSITIONAL_FEATURE_NAMES
        )
        # Should not raise
        _validate_pass_model_features(
            features_with_positional,
            partner_feature_names=[],
            has_interactions=False,
            has_positional=False,
        )

    def test_validate_pass_model_selected_positional_subset(self):
        """Pass model with forward-selected positional subset validates.

        Regression test: forward selection keeps seat_rel_2 but drops
        current_high_bid. The validator must accept this.
        """
        selected = list(_HAND_FEATURE_NAMES) + ["seat_rel_2"]
        # Should not raise
        _validate_pass_model_features(
            selected,
            partner_feature_names=[],
            has_interactions=False,
            has_positional=False,
        )

    def test_validate_artifact_features_r0_selected_subset(self):
        """Forward-selected R0 artifact with 3 hand features validates."""
        subset = ["bowers", "trump_count", "offsuit_aces"]
        model_features = subset + list(ACTION_FEATURE_NAMES)
        partner_names, has_positional = _validate_artifact_features(
            model_features, has_interactions=False
        )
        assert partner_names == []
        assert has_positional is False

    def test_validate_pass_model_r0_selected_subset(self):
        """Forward-selected R0 pass model with 2 hand features validates."""
        subset = ["bowers", "quick_tricks"]
        _validate_pass_model_features(
            subset,
            partner_feature_names=[],
            has_interactions=False,
            has_positional=False,
        )

    def test_validate_artifact_features_r0_unknown_feature_raises(self):
        """R0 artifact with unknown feature (not in hand set) raises."""
        bad_features = ["bowers", "UNKNOWN_FEATURE"] + list(ACTION_FEATURE_NAMES)
        with pytest.raises(ValueError, match="unknown state features"):
            _validate_artifact_features(bad_features, has_interactions=False)

    def test_validate_artifact_features_selected_with_positional_subset(self):
        """Forward-selected model with seat_rel_2 but no current_high_bid validates.

        Regression test: forward selection from the full 69-feature set may
        keep positional features (e.g. seat_rel_2) while dropping
        current_high_bid. The validator must accept this.
        """
        selected = ["bowers", "trump_count", "seat_rel_2"]
        model_features = selected + list(ACTION_FEATURE_NAMES)
        partner_names, has_positional = _validate_artifact_features(
            model_features, has_interactions=False
        )
        assert has_positional is False
        assert partner_names == []

    def test_validate_artifact_features_selected_with_partner_v2(self):
        """Forward-selected model with partner v2 features but no positional validates."""
        # Simulate forward selection keeping some hand + partner_passed (no positional)
        selected = ["bowers", "trump_count", "partner_passed"]
        model_features = selected + list(ACTION_FEATURE_NAMES)
        partner_names, has_positional = _validate_artifact_features(
            model_features, has_interactions=False
        )
        assert has_positional is False
        # partner_names inferred as empty because _infer_partner_features
        # only detects partners when positional features are present
        assert partner_names == []

    def test_validate_artifact_features_selected_with_position(self):
        """Forward-selected model with position features but no positional validates."""
        # Simulate forward selection keeping hand + auction_position (no positional)
        selected = ["bowers", "trump_count", "auction_position"]
        model_features = selected + list(ACTION_FEATURE_NAMES)
        partner_names, has_positional = _validate_artifact_features(
            model_features, has_interactions=False
        )
        assert has_positional is False
        assert partner_names == []

    def test_validate_artifact_features_selected_with_partner_and_position(self):
        """Forward-selected model with partner v2 + position features validates."""
        selected = [
            "bowers",
            "trump_count",
            "partner_passed",
            "partner_level_high",
            "auction_position",
            "is_dealer",
        ]
        model_features = selected + list(ACTION_FEATURE_NAMES)
        partner_names, has_positional = _validate_artifact_features(
            model_features, has_interactions=False
        )
        assert has_positional is False
        assert partner_names == []

    def test_validate_pass_model_selected_with_partner_v2(self):
        """Forward-selected pass model with partner v2 features validates."""
        selected = ["bowers", "trump_count", "partner_passed"]
        _validate_pass_model_features(
            selected,
            partner_feature_names=[],
            has_interactions=False,
            has_positional=False,
        )

    def test_validate_pass_model_selected_with_position(self):
        """Forward-selected pass model with position features validates."""
        selected = ["bowers", "auction_position", "is_dealer"]
        _validate_pass_model_features(
            selected,
            partner_feature_names=[],
            has_interactions=False,
            has_positional=False,
        )
