"""Review loop driver — main orchestrator for the autonomous review loop.

Runs as a background process launched by post-pr-review-loop.sh:
1. Loads state from disk (or initializes if new)
2. Loops: advance one step, sleep when polling, until terminal or timeout
3. Saves state and round artifacts after each step
4. Maximum runtime: 15 minutes

Idempotent: duplicate triggers are harmless (sentinel file in hook).
Entry point: python scripts/internal/review_driver.py --pr <N> --trigger <event>

Adapters:
- codex_review_adapter: Codex CLI invocation + output parsing
- claude_fix_adapter: deterministic fix application + commit
"""

from __future__ import annotations

import argparse
import json
import logging
import re
import subprocess
import sys
import time
from pathlib import Path

from review_state import (
    TERMINAL_STATES,
    ReviewLoopState,
    ReviewMode,
    ReviewState,
    load_state,
    round_dir,
    save_state,
)

logger = logging.getLogger("review_driver")

# Failure state categories that should trigger agent notification
_FAILURE_STATES = frozenset(
    {
        ReviewState.STOPPED_CI_FAILURE,
        ReviewState.STOPPED_REVIEW_FAILURE,
        ReviewState.STOPPED_MAX_ITERATIONS,
        ReviewState.STOPPED_NO_PROGRESS,
    }
)


def _write_failure_sentinel(loop_state: ReviewLoopState) -> None:
    """Write a FAILED sentinel file so the notification hook can alert the agent.

    Only writes for terminal failure states. The sentinel is a one-line summary
    read by .claude/hooks/post-tool-daemon-notify.sh.
    """
    if loop_state.current_state not in _FAILURE_STATES:
        return

    state_dir = Path(".claude/runtime/review_loops") / f"pr_{loop_state.pr_number}"
    state_dir.mkdir(parents=True, exist_ok=True)
    sentinel = state_dir / "FAILED"

    reason = loop_state.stop_reason or loop_state.current_state.value
    label = loop_state.current_state.value.upper()
    summary = f"{label}: {reason}"

    try:
        sentinel.write_text(summary + "\n")
        logger.info("PR #%d: wrote failure sentinel: %s", loop_state.pr_number, summary)
    except OSError:
        logger.warning("PR #%d: failed to write failure sentinel", loop_state.pr_number)


def _publish_status(pr_number: int, state: str, description: str) -> bool:
    """Publish a review status to GitHub, logging errors but not raising.

    Args:
        pr_number: PR number.
        state: GitHub API state ("pending", "success", "failure").
        description: Short description (max 140 chars).

    Returns:
        True if published successfully, False otherwise.
    """
    try:
        from github_pr_state import publish_review_status

        ok = publish_review_status(pr_number, state, description[:140])
        if not ok:
            logger.warning("PR #%d: failed to publish status %s", pr_number, state)
        return ok
    except Exception:
        logger.exception("PR #%d: error publishing status %s", pr_number, state)
        return False


def _create_follow_up_issues(
    pr_number: int,
    findings: list[dict],
) -> list[str]:
    """Create GitHub issues for non-blocking findings (P2/WARN).

    Groups findings by category and creates one issue per category label.

    Args:
        pr_number: PR number the findings came from.
        findings: List of finding dicts with severity, category, etc.

    Returns:
        List of URLs for created issues.
    """
    warn_findings = [f for f in findings if f.get("severity") == "P2"]
    if not warn_findings:
        return []

    # Group by category -> label mapping
    _CATEGORY_LABEL_MAP = {
        "correctness": "fix:bug",
        "convention": "fix:convention",
        "test": "fix:test",
        "process": "fix:process",
        "provenance": "fix:docs",
    }

    by_label: dict[str, list[dict]] = {}
    for f in warn_findings:
        cat = f.get("category", "convention")
        label = _CATEGORY_LABEL_MAP.get(cat, "fix:convention")
        by_label.setdefault(label, []).append(f)

    issue_urls: list[str] = []
    for label, cat_findings in by_label.items():
        # Build issue body
        findings_table = (
            "| ID | File | Line | Description |\n|----|------|------|-------------|\n"
        )
        for f in cat_findings:
            findings_table += (
                f"| {f.get('check_id', '-')} "
                f"| {f.get('file', '-')} "
                f"| {f.get('line', '-')} "
                f"| {f.get('message', '-')} |\n"
            )

        body = (
            f"## Follow-up: PR #{pr_number}\n\n"
            "Findings from autonomous review loop that should be "
            "addressed post-merge.\n\n"
            f"### Findings\n{findings_table}\n"
            "---\n"
            f"*Auto-generated by review loop. Original PR: #{pr_number}*"
        )

        title = f"fix({label}): follow-up for PR #{pr_number}"

        # Try with labels first, fall back to without
        result = subprocess.run(
            [
                "gh",
                "issue",
                "create",
                "--title",
                title,
                "--label",
                f"{label},follow-up",
                "--body",
                body,
            ],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            # Retry without labels (they may not exist)
            result = subprocess.run(
                [
                    "gh",
                    "issue",
                    "create",
                    "--title",
                    title,
                    "--body",
                    body,
                ],
                capture_output=True,
                text=True,
            )

        if result.returncode == 0:
            url = result.stdout.strip()
            issue_urls.append(url)
            logger.info("Created follow-up issue: %s", url)
        else:
            logger.warning(
                "Failed to create follow-up issue for %s: %s",
                label,
                result.stderr[:200],
            )

    return issue_urls


def classify_review_mode(changed_files: list[str]) -> ReviewMode:
    """Determine review mode from the set of changed files.

    Code files always trigger STANDARD mode. Plan/report-only PRs
    get specialized audit modes.
    """
    has_code = any(
        f.endswith(".py")
        and (f.startswith("src/") or f.startswith("scripts/") or f.startswith("tests/"))
        for f in changed_files
    )
    has_reports = any(f.startswith("docs/04_reports/") for f in changed_files)
    has_plans = any(f.startswith("plans/") for f in changed_files)

    # Code files always get standard review (most comprehensive)
    if has_code:
        return ReviewMode.STANDARD
    if has_reports:
        return ReviewMode.REPORT_AUDIT
    if has_plans:
        return ReviewMode.PLAN_AUDIT
    return ReviewMode.STANDARD


def initialize_state(
    pr_number: int,
    branch: str,
    mode: ReviewMode,
    max_iterations: int = 3,
    *,
    head_sha: str | None = None,
) -> ReviewLoopState:
    """Create initial state for a new review loop.

    Args:
        pr_number: PR number.
        branch: Branch name.
        mode: Review mode.
        max_iterations: Maximum review iterations.
        head_sha: HEAD SHA at loop start (for idempotency tracking).
    """
    run_id = None
    if head_sha:
        run_id = f"pr_{pr_number}_{head_sha[:7]}"
    return ReviewLoopState(
        pr_number=pr_number,
        branch=branch,
        mode=mode.value,
        state=ReviewState.INITIALIZED.value,
        max_iterations=max_iterations,
        initial_head_sha=head_sha,
        current_head_sha=head_sha,
        run_id=run_id,
    )


def step(
    loop_state: ReviewLoopState,
    *,
    base_dir: Path | None = None,
) -> ReviewLoopState:
    """Advance the state machine by one step.

    This is the main dispatch function. Each call makes bounded progress
    (one transition) and returns the updated state.

    Args:
        loop_state: Current state.
        base_dir: Override for state persistence directory.

    Returns:
        Updated state (also persisted to disk).
    """
    current = loop_state.current_state

    # Terminal states → no-op
    if current in TERMINAL_STATES:
        logger.info(
            "PR #%d: terminal state %s — no-op",
            loop_state.pr_number,
            current.value,
        )
        return loop_state

    # Check max iterations (global stop condition)
    if loop_state.iteration_count >= loop_state.max_iterations:
        _publish_status(
            loop_state.pr_number,
            "failure",
            f"Review stopped -- max iterations ({loop_state.max_iterations})",
        )
        loop_state.transition(ReviewState.STOPPED_MAX_ITERATIONS)
        loop_state.stop_reason = f"Hit max iterations ({loop_state.max_iterations})"
        _post_review_comment(loop_state, [], "blocked")
        save_state(loop_state, base_dir)
        logger.warning(
            "PR #%d: stopped -- max iterations (%d)",
            loop_state.pr_number,
            loop_state.max_iterations,
        )
        return loop_state

    # Dispatch by current state
    if current == ReviewState.INITIALIZED:
        return _step_initialized(loop_state, base_dir)
    elif current == ReviewState.PR_OPEN:
        return _step_pr_open(loop_state, base_dir)
    elif current == ReviewState.WAITING_FOR_CI:
        return _step_waiting_for_ci(loop_state, base_dir)
    elif current == ReviewState.WAITING_FOR_CODEX:
        return _step_waiting_for_codex(loop_state, base_dir)
    elif current == ReviewState.SCORING_FINDINGS:
        return _step_scoring_findings(loop_state, base_dir)
    elif current == ReviewState.APPLYING_FIXES:
        return _step_applying_fixes(loop_state, base_dir)
    elif current == ReviewState.RETESTING:
        return _step_retesting(loop_state, base_dir)
    elif current == ReviewState.READY_TO_MERGE:
        return _step_ready_to_merge(loop_state, base_dir)
    else:
        logger.error(
            "PR #%d: unexpected state %s",
            loop_state.pr_number,
            current.value,
        )
        return loop_state


def _step_initialized(
    loop_state: ReviewLoopState,
    base_dir: Path | None,
) -> ReviewLoopState:
    """INITIALIZED → PR_OPEN: PR exists, transition to open."""
    _publish_status(loop_state.pr_number, "pending", "Review loop started")
    loop_state.transition(ReviewState.PR_OPEN)
    save_state(loop_state, base_dir)
    logger.info("PR #%d: initialized → pr_open", loop_state.pr_number)
    return loop_state


# Regex for explicit plan opt-out markers (N/A, none, dash, em-dash)
_PLAN_OPTOUT_RE = re.compile(r"^(?:N/?A|none|-)$", re.IGNORECASE)

# Minimum content length (after stripping headers/comments) for a non-trivial plan
_PLAN_MIN_CONTENT_LEN = 50


def parse_plan_reference(pr_body: str) -> tuple[str | None, bool]:
    """Extract plan file path from PR body's ``## Plan`` section.

    Handles:
    - Plain path: ``plans/sessions/2026-03-14_foo.md``
    - Backtick-quoted: ```plans/sessions/2026-03-14_foo.md```
    - Markdown link: ``[Plan](plans/sessions/2026-03-14_foo.md)``
    - List item prefix: ``- plans/sessions/...``
    - Explicit opt-out: ``N/A``, ``none``, ``-``

    Args:
        pr_body: Full PR description text.

    Returns:
        Tuple of (path or None, opted_out). If opted_out is True,
        the author explicitly marked the plan as N/A.
    """
    # Find ## Plan section (up to next ## heading or end of body)
    plan_match = re.search(
        r"^## Plan\s*\n(.*?)(?=^## |\Z)",
        pr_body,
        re.MULTILINE | re.DOTALL,
    )
    if not plan_match:
        return None, False

    section = plan_match.group(1)
    # Strip HTML comments
    section = re.sub(r"<!--.*?-->", "", section, flags=re.DOTALL).strip()

    if not section:
        return None, False

    # Check for explicit opt-out BEFORE stripping list markers
    # (a bare "-" is the unfilled template placeholder, not a list prefix)
    clean_for_optout = re.sub(r"^[-*]\s*", "", section).strip()
    if _PLAN_OPTOUT_RE.match(section) or (not clean_for_optout):
        return None, True

    # Strip leading list marker for path extraction
    section = clean_for_optout

    # Try backtick-quoted path
    backtick_match = re.search(r"`([^`]+\.md)`", section)
    if backtick_match:
        return backtick_match.group(1), False

    # Try markdown link
    link_match = re.search(r"\[.*?\]\(([^)]+\.md)\)", section)
    if link_match:
        return link_match.group(1), False

    # Try plain path (looks like a relative file path ending in .md)
    path_match = re.search(r"((?:plans|docs)/\S+\.md)", section)
    if path_match:
        return path_match.group(1), False

    return None, False


def validate_plan(
    pr_number: int,
    *,
    repo_root: Path | None = None,
) -> tuple[str | None, list[dict]]:
    """Validate the plan reference declared in a PR's body.

    Checks:
    1. Plan reference is present in the PR body (P2 if missing).
    2. Referenced plan file exists on disk (P1 if broken reference).
    3. Plan file has non-trivial content (P2 if empty/boilerplate).

    Failures in fetching the PR body are non-blocking (logged and skipped).

    Args:
        pr_number: PR number to validate.
        repo_root: Repository root for file existence checks.

    Returns:
        Tuple of (plan_path or None, list of finding dicts).
    """
    from github_pr_state import get_pr_body

    if repo_root is None:
        repo_root = Path.cwd()

    findings: list[dict] = []

    try:
        body = get_pr_body(pr_number)
    except Exception:
        logger.warning(
            "PR #%d: failed to fetch PR body — skipping plan validation",
            pr_number,
        )
        return None, []

    plan_path, opted_out = parse_plan_reference(body)

    if opted_out:
        # Explicit N/A — no finding
        return None, []

    if plan_path is None:
        findings.append(
            {
                "severity": "P2",
                "file": "<PR body>",
                "line": 0,
                "category": "process",
                "check_id": "PV1",
                "message": "No plan reference in PR body — add a plan path or N/A",
                "raw_source": "plan_validation",
            }
        )
        return None, findings

    # Check if plan file exists.
    # NOTE: Demoted from P1 (blocking) to P2 (warning) because the review
    # driver runs in the worktree where `gh pr create` was invoked, which may
    # not have the PR branch checked out. The plan file may exist on the PR
    # branch but not in the stale worktree. See plans/sessions/
    # 2026-03-18_review-loop-parse-fixes.md for full analysis.
    full_path = repo_root / plan_path
    if not full_path.exists():
        findings.append(
            {
                "severity": "P2",
                "file": plan_path,
                "line": 0,
                "category": "process",
                "check_id": "PV2",
                "message": f"Plan file does not exist: {plan_path}",
                "raw_source": "plan_validation",
            }
        )
        return plan_path, findings

    # Check if plan file has non-trivial content
    content = full_path.read_text()
    # Strip markdown headers and HTML comments to measure real content
    stripped = re.sub(r"<!--.*?-->", "", content, flags=re.DOTALL)
    stripped = re.sub(r"^#+\s.*$", "", stripped, flags=re.MULTILINE)
    stripped = re.sub(r"^\*\*.*?\*\*:?", "", stripped, flags=re.MULTILINE)
    stripped = stripped.strip()

    if len(stripped) < _PLAN_MIN_CONTENT_LEN:
        findings.append(
            {
                "severity": "P2",
                "file": plan_path,
                "line": 0,
                "category": "process",
                "check_id": "PV3",
                "message": "Plan file appears to be empty or boilerplate only",
                "raw_source": "plan_validation",
            }
        )

    return plan_path, findings


def _parse_plan_files(plan_path: str, repo_root: Path) -> list[str]:
    """Read a plan file and extract declared file paths from ``## Files``.

    Each line in the ``## Files`` section is expected to start with ``- ``
    and may contain a backtick-quoted path (e.g., `` `scripts/internal/foo.py` ``)
    or a plain path before the first `` — `` or `` - `` delimiter.

    Args:
        plan_path: Relative path to the plan file (from repo root).
        repo_root: Repository root directory.

    Returns:
        List of declared file paths (relative to repo root).
    """
    full_path = repo_root / plan_path
    if not full_path.exists():
        return []

    content = full_path.read_text()

    # Find ## Files section (up to next ## heading or end)
    files_match = re.search(
        r"^## Files\s*\n(.*?)(?=^## |\Z)",
        content,
        re.MULTILINE | re.DOTALL,
    )
    if not files_match:
        return []

    section = files_match.group(1)
    declared: list[str] = []

    for line in section.strip().split("\n"):
        line = line.strip()
        if not line.startswith("- "):
            continue
        line = line[2:].strip()

        # Try backtick-quoted path first
        backtick_match = re.search(r"`([^`]+)`", line)
        if backtick_match:
            declared.append(backtick_match.group(1))
            continue

        # Try plain path (before any em-dash or description separator)
        # Split on " — " or " - " to separate path from description
        path_part = re.split(r"\s+[—-]\s+", line, maxsplit=1)[0].strip()
        if path_part and "/" in path_part:
            declared.append(path_part)

    return declared


def check_scope_drift(
    changed_files: list[str],
    declared_files: list[str],
) -> list[dict]:
    """Compare PR changed files against plan-declared files.

    Files that appear in the PR diff but are not listed in the plan's
    ``## Files`` section are reported as P2 (non-blocking) scope-drift
    findings.

    Args:
        changed_files: Files changed in the PR (from git/GitHub).
        declared_files: Files declared in the plan's ``## Files`` section.

    Returns:
        List of P2 finding dicts for undeclared files.
    """
    if not declared_files:
        # No declared files = no scope contract to check against
        return []

    declared_set = set(declared_files)
    findings: list[dict] = []

    for f in sorted(set(changed_files) - declared_set):
        findings.append(
            {
                "severity": "P2",
                "file": f,
                "line": 0,
                "category": "process",
                "check_id": "SD1",
                "message": f"File not declared in plan: {f}",
                "raw_source": "scope_drift",
            }
        )

    return findings


def _format_review_comment(
    loop_state: ReviewLoopState,
    all_findings: list[dict],
    status: str,
) -> str:
    """Build a structured markdown comment for the PR.

    Args:
        loop_state: Current review loop state.
        all_findings: All findings (blocking + warnings) to include.
        status: "blocked" or "passed".

    Returns:
        Markdown body for the PR comment (includes the dedup marker).
    """
    from github_pr_state import REVIEW_COMMENT_MARKER

    if status == "blocked":
        header = "## Review Loop -- Blocked"
    else:
        header = "## Review Loop -- Passed"

    lines = [
        REVIEW_COMMENT_MARKER,
        header,
        "",
    ]

    # Head SHA for traceability
    sha = loop_state.current_head_sha or loop_state.initial_head_sha or "unknown"
    lines.append(f"**Head SHA:** `{sha}`")
    lines.append(f"**State:** `{loop_state.current_state.value}`")
    if loop_state.stop_reason:
        lines.append(f"**Reason:** {loop_state.stop_reason}")
    lines.append("")

    # Separate blocking vs warning findings
    blockers = [f for f in all_findings if f.get("severity") in ("P0", "P1")]
    warnings = [f for f in all_findings if f.get("severity") == "P2"]

    if blockers:
        lines.append("### Blocking Findings")
        lines.append("")
        lines.append("| ID | Severity | File | Message |")
        lines.append("|----|----------|------|---------|")
        for f in blockers:
            lines.append(
                f"| {f.get('check_id', '-')} "
                f"| {f.get('severity', '-')} "
                f"| {f.get('file', '-')} "
                f"| {f.get('message', '-')} |"
            )
        lines.append("")

    if warnings:
        lines.append("### Warnings")
        lines.append("")
        lines.append("| ID | File | Message |")
        lines.append("|----|------|---------|")
        for f in warnings:
            lines.append(
                f"| {f.get('check_id', '-')} "
                f"| {f.get('file', '-')} "
                f"| {f.get('message', '-')} |"
            )
        lines.append("")

    if not blockers and not warnings:
        lines.append("No findings.")
        lines.append("")

    # Recovery command
    lines.append("### Recovery")
    lines.append("")
    lines.append("```bash")
    lines.append(
        f"python scripts/internal/review_driver.py "
        f"--pr {loop_state.pr_number} --trigger manual"
    )
    lines.append("```")
    lines.append("")
    lines.append(
        f"*Auto-generated by review loop (iteration "
        f"{loop_state.iteration_count}/{loop_state.max_iterations}).*"
    )

    return "\n".join(lines)


def _post_review_comment(
    loop_state: ReviewLoopState,
    all_findings: list[dict],
    status: str,
) -> None:
    """Post a structured review comment to the PR.

    Logs errors but does not raise on failure.

    Args:
        loop_state: Current review loop state.
        all_findings: All findings to include in the comment.
        status: "blocked" or "passed".
    """
    try:
        from github_pr_state import upsert_review_comment

        body = _format_review_comment(loop_state, all_findings, status)
        upsert_review_comment(loop_state.pr_number, body)
    except Exception:
        logger.exception("PR #%d: failed to post review comment", loop_state.pr_number)


def _step_pr_open(
    loop_state: ReviewLoopState,
    base_dir: Path | None,
) -> ReviewLoopState:
    """PR_OPEN → WAITING_FOR_CI: Run plan validation + prechecks."""
    from deterministic_prechecks import check_diff, get_blocking_findings

    # 0. Fetch PR-scoped changed files (used by scope-drift + prechecks)
    pr_changed_files: list[str] | None = None
    try:
        from github_pr_state import get_pr_changed_files

        pr_changed_files = get_pr_changed_files(loop_state.pr_number)
    except Exception:
        logger.warning(
            "PR #%d: failed to fetch PR files — prechecks will use git diff",
            loop_state.pr_number,
        )

    # 0a. Validate plan reference (non-blocking on fetch failures)
    plan_path, plan_findings = validate_plan(loop_state.pr_number)
    if plan_path:
        loop_state.plan_path = plan_path

    # 0b. Scope-drift check (only if we have a valid plan path + PR files)
    scope_drift_findings: list[dict] = []
    if plan_path and pr_changed_files is not None:
        try:
            declared_files = _parse_plan_files(plan_path, Path.cwd())
            scope_drift_findings = check_scope_drift(pr_changed_files, declared_files)
            if scope_drift_findings:
                logger.info(
                    "PR #%d: scope drift detected — %d undeclared files",
                    loop_state.pr_number,
                    len(scope_drift_findings),
                )
        except Exception:
            logger.warning(
                "PR #%d: scope-drift check failed — skipping",
                loop_state.pr_number,
            )

    # 1. Run deterministic prechecks (using PR-scoped files when available)
    findings = check_diff(mode=loop_state.mode, changed_files=pr_changed_files)
    blocking = get_blocking_findings(findings)

    # Merge plan validation findings (already dicts) with precheck Finding objects
    # Plan findings with P1 severity count as blocking
    plan_blocking = [f for f in plan_findings if f.get("severity") in ("P0", "P1")]

    # Save all precheck + plan validation + scope-drift results for this round
    rdir = round_dir(loop_state.pr_number, loop_state.iteration_count + 1, base_dir)
    rdir.mkdir(parents=True, exist_ok=True)
    all_findings_dicts = (
        [f.to_dict() for f in findings] + plan_findings + scope_drift_findings
    )
    with open(rdir / "prechecks.json", "w") as f:
        json.dump(all_findings_dicts, f, indent=2)

    all_blocking = list(blocking) + plan_blocking
    if all_blocking:
        # Blocking prechecks/plan issues -> stop
        _publish_status(
            loop_state.pr_number,
            "failure",
            f"Blocking prechecks: {len(all_blocking)} findings",
        )
        loop_state.transition(ReviewState.STOPPED_CI_FAILURE)
        loop_state.stop_reason = (
            f"Blocking precheck/plan failures: {len(all_blocking)} findings"
        )
        _post_review_comment(loop_state, all_findings_dicts, "blocked")
        save_state(loop_state, base_dir)
        logger.warning(
            "PR #%d: blocking prechecks (%d findings) -- stopped",
            loop_state.pr_number,
            len(all_blocking),
        )
        return loop_state

    # 2. Prechecks passed -> wait for CI (remote)
    # NOTE: Local `make check` was removed because the review loop runs in the
    # main checkout (not the PR worktree), so local validation hits dirty state
    # and stale fixtures unrelated to the PR.  GitHub CI runs on a clean checkout
    # and is the authoritative build gate — the WAITING_FOR_CI step polls it.
    loop_state.transition(ReviewState.WAITING_FOR_CI)
    save_state(loop_state, base_dir)
    logger.info("PR #%d: pr_open -> waiting_for_ci", loop_state.pr_number)
    return loop_state


def _step_waiting_for_ci(
    loop_state: ReviewLoopState,
    base_dir: Path | None,
) -> ReviewLoopState:
    """WAITING_FOR_CI → WAITING_FOR_CODEX or STOPPED_CI_FAILURE."""
    from github_pr_state import get_ci_status

    ci_status = get_ci_status(loop_state.pr_number)
    loop_state.last_ci_status = ci_status

    if ci_status == "pending":
        # Not ready yet — save state and exit (resume on next trigger)
        save_state(loop_state, base_dir)
        logger.info("PR #%d: CI pending — will resume", loop_state.pr_number)
        return loop_state

    if ci_status == "failure":
        _publish_status(loop_state.pr_number, "failure", "CI failed")
        loop_state.transition(ReviewState.STOPPED_CI_FAILURE)
        loop_state.stop_reason = "CI failed"
        _post_review_comment(loop_state, [], "blocked")
        save_state(loop_state, base_dir)
        logger.warning("PR #%d: CI failed -- stopped", loop_state.pr_number)
        return loop_state

    if ci_status == "success":
        loop_state.transition(ReviewState.WAITING_FOR_CODEX)
        save_state(loop_state, base_dir)
        logger.info(
            "PR #%d: waiting_for_ci → waiting_for_codex",
            loop_state.pr_number,
        )
        return loop_state

    # Unknown CI status — treat as pending
    save_state(loop_state, base_dir)
    logger.info(
        "PR #%d: CI status unknown (%s) — will resume",
        loop_state.pr_number,
        ci_status,
    )
    return loop_state


def _step_waiting_for_codex(
    loop_state: ReviewLoopState,
    base_dir: Path | None,
) -> ReviewLoopState:
    """WAITING_FOR_CODEX → SCORING_FINDINGS or STOPPED_REVIEW_FAILURE.

    Invokes Codex CLI, parses findings, and transitions to SCORING_FINDINGS
    for confidence-based filtering. On invocation failure, retries or stops.
    """
    from codex_review_adapter import invoke_codex_cli, save_review_result

    iteration = loop_state.iteration_count + 1

    _publish_status(
        loop_state.pr_number,
        "pending",
        f"Codex CLI review in progress (round {iteration})",
    )

    result = invoke_codex_cli(mode=loop_state.mode)
    save_review_result(result, loop_state.pr_number, iteration, base_dir)

    if not result.success:
        loop_state.codex_retry_count += 1
        if loop_state.codex_retry_count >= 3:
            _publish_status(
                loop_state.pr_number,
                "failure",
                f"Codex CLI failed {loop_state.codex_retry_count} times",
            )
            loop_state.transition(ReviewState.STOPPED_REVIEW_FAILURE)
            loop_state.last_codex_status = "failed"
            loop_state.stop_reason = (
                f"Codex CLI failed {loop_state.codex_retry_count} times: {result.error}"
            )
            _post_review_comment(loop_state, [], "blocked")
            save_state(loop_state, base_dir)
            logger.warning(
                "PR #%d: Codex CLI failed %d times -- stopped",
                loop_state.pr_number,
                loop_state.codex_retry_count,
            )
        else:
            loop_state.last_codex_status = "retry"
            save_state(loop_state, base_dir)
            logger.info(
                "PR #%d: Codex CLI failed (attempt %d/%d) — will retry",
                loop_state.pr_number,
                loop_state.codex_retry_count,
                3,
            )
        return loop_state

    # Reset retry count on success
    loop_state.codex_retry_count = 0
    loop_state.last_codex_status = "success"

    # Transition to SCORING_FINDINGS for confidence-based P2 filtering
    loop_state.transition(ReviewState.SCORING_FINDINGS)
    save_state(loop_state, base_dir)
    logger.info(
        "PR #%d: Codex review complete (%d findings) → scoring_findings",
        loop_state.pr_number,
        len(result.findings),
    )
    return loop_state


def _step_scoring_findings(
    loop_state: ReviewLoopState,
    base_dir: Path | None,
) -> ReviewLoopState:
    """SCORING_FINDINGS → APPLYING_FIXES or READY_TO_MERGE.

    Loads Codex findings, runs confidence scoring to filter low-confidence
    P2 findings, then decides next transition:
    - Blocking findings remain → APPLYING_FIXES
    - No blocking findings → READY_TO_MERGE (with follow-up issues for P2s)
    """
    from codex_review_adapter import CodexFinding, get_blocking_findings
    from confidence_scorer import save_scoring_report, score_findings
    from review_state import compute_findings_hash

    iteration = loop_state.iteration_count + 1

    # Load findings from this round's Codex review
    rdir = round_dir(loop_state.pr_number, iteration, base_dir)
    codex_path = rdir / "codex_review.json"

    if codex_path.exists():
        with open(codex_path) as f:
            review_data = json.load(f)
        raw_findings = review_data.get("findings", [])
        parse_confidence = review_data.get("parse_confidence", "structured")
    else:
        logger.warning(
            "PR #%d: no codex_review.json found for round %d",
            loop_state.pr_number,
            iteration,
        )
        raw_findings = []
        parse_confidence = "structured"

    # If review result is degraded (unparseable output or backend error),
    # publish advisory status and proceed to merge — CI is the real gate.
    # This prevents "I don't know" from being treated as "clean pass" or "blocked".
    if parse_confidence in ("unparseable", "backend_error"):
        desc = f"Review degraded — Codex output {parse_confidence} (advisory)"
        _publish_status(loop_state.pr_number, "success", desc[:140])
        loop_state.transition(ReviewState.READY_TO_MERGE)
        _post_review_comment(loop_state, [], "passed")
        save_state(loop_state, base_dir)
        logger.warning(
            "PR #%d: Codex review degraded (parse_confidence=%s) — "
            "advisory skip, CI gate remains authoritative",
            loop_state.pr_number,
            parse_confidence,
        )
        return loop_state

    # Get PR diff for diff-aware scoring
    diff_result = subprocess.run(
        ["git", "diff", "origin/main...HEAD"],
        capture_output=True,
        text=True,
    )
    pr_diff = diff_result.stdout if diff_result.returncode == 0 else ""

    # Run confidence scoring
    filtered_findings, scored = score_findings(raw_findings, pr_diff)

    # Save scoring report for audit trail
    save_scoring_report(scored, rdir / "confidence_scoring.json")

    # Save filtered findings for downstream fix stage (ensures
    # _step_applying_fixes uses scored findings, not raw Codex output)
    filtered_path = rdir / "codex_review_filtered.json"
    with open(filtered_path, "w") as f:
        json.dump({"findings": filtered_findings}, f, indent=2)

    filtered_count = sum(1 for s in scored if s.filtered)
    if filtered_count > 0:
        logger.info(
            "PR #%d: confidence scoring filtered %d/%d P2 findings",
            loop_state.pr_number,
            filtered_count,
            len(scored),
        )

    # Reconstruct CodexFinding objects from filtered dicts for blocking check
    codex_findings = []
    for fd in filtered_findings:
        codex_findings.append(
            CodexFinding(
                severity=fd.get("severity", "P2"),
                file=fd.get("file", ""),
                line=fd.get("line", 0),
                category=fd.get("category", "convention"),
                check_id=fd.get("check_id"),
                message=fd.get("message", ""),
                raw_source=fd.get("raw_source", "codex_cli"),
            )
        )

    blocking = get_blocking_findings(codex_findings)

    if not blocking:
        # Create follow-up issues for remaining P2 findings
        p2_count = sum(1 for f in filtered_findings if f.get("severity") == "P2")
        follow_up_urls = _create_follow_up_issues(
            loop_state.pr_number, filtered_findings
        )

        # Publish success status with finding summary
        if p2_count > 0:
            desc = (
                f"Review passed -- {p2_count} warnings "
                f"({len(follow_up_urls)} follow-up issues created)"
            )
            if filtered_count > 0:
                desc += f", {filtered_count} low-confidence filtered"
        else:
            desc = "Review passed -- clean"
            if filtered_count > 0:
                desc += f" ({filtered_count} low-confidence filtered)"
        _publish_status(loop_state.pr_number, "success", desc[:140])

        loop_state.transition(ReviewState.READY_TO_MERGE)
        _post_review_comment(loop_state, filtered_findings, "passed")
        save_state(loop_state, base_dir)
        logger.info(
            "PR #%d: no blocking findings after scoring -> ready_to_merge",
            loop_state.pr_number,
        )
        return loop_state

    # Check for stagnation before advancing to fix round
    findings_dicts = [f.to_dict() for f in codex_findings]
    current_hash = compute_findings_hash(findings_dicts)

    if current_hash == loop_state.last_findings_hash:
        _publish_status(
            loop_state.pr_number,
            "failure",
            "Review stopped -- no progress after fixes",
        )
        loop_state.transition(ReviewState.STOPPED_NO_PROGRESS)
        loop_state.stop_reason = (
            f"Same findings hash ({current_hash}) -- no progress after fixes"
        )
        _post_review_comment(loop_state, findings_dicts, "blocked")
        save_state(loop_state, base_dir)
        logger.warning(
            "PR #%d: stagnation detected (hash=%s) -- stopped",
            loop_state.pr_number,
            current_hash,
        )
        return loop_state

    loop_state.last_findings_hash = current_hash
    loop_state.transition(ReviewState.APPLYING_FIXES)
    save_state(loop_state, base_dir)
    logger.info(
        "PR #%d: %d blocking findings after scoring → applying_fixes",
        loop_state.pr_number,
        len(blocking),
    )
    return loop_state


def _step_applying_fixes(
    loop_state: ReviewLoopState,
    base_dir: Path | None,
) -> ReviewLoopState:
    """APPLYING_FIXES → RETESTING.

    Loads the latest Codex findings, applies auto-fixable patterns,
    commits, and pushes. Transitions to RETESTING on success.
    """
    from claude_fix_adapter import (
        apply_fixes,
        commit_fixes,
        push_fixes,
        save_fix_summary,
    )

    iteration = loop_state.iteration_count + 1

    # Prefer scored/filtered findings over raw Codex output.
    # _step_scoring_findings saves codex_review_filtered.json after
    # confidence scoring; fall back to raw codex_review.json for
    # backward compatibility with rounds that pre-date scoring.
    rdir = round_dir(loop_state.pr_number, iteration, base_dir)
    filtered_path = rdir / "codex_review_filtered.json"
    codex_path = rdir / "codex_review.json"

    if filtered_path.exists():
        with open(filtered_path) as f:
            review_data = json.load(f)
        findings = review_data.get("findings", [])
    elif codex_path.exists():
        with open(codex_path) as f:
            review_data = json.load(f)
        findings = review_data.get("findings", [])
    else:
        logger.warning(
            "PR #%d: no findings file found for round %d",
            loop_state.pr_number,
            iteration,
        )
        findings = []

    # Apply auto-fixable patterns
    summary = apply_fixes(findings)
    save_fix_summary(summary, loop_state.pr_number, iteration, base_dir)

    if summary.fixes_applied == 0:
        # No auto-fixes possible — still transition to RETESTING
        # (manual fixes may have been applied externally)
        logger.info(
            "PR #%d: no auto-fixes applied (%d skipped) — retesting anyway",
            loop_state.pr_number,
            summary.fixes_skipped,
        )
        loop_state.iteration_count = iteration
        loop_state.transition(ReviewState.RETESTING)
        save_state(loop_state, base_dir)
        return loop_state

    # Commit and push
    commit_fixes(summary, loop_state.pr_number, iteration)
    if summary.commit_sha:
        push_fixes(loop_state.branch)
        loop_state.last_head_sha = summary.commit_sha
        loop_state.current_head_sha = summary.commit_sha

    loop_state.iteration_count = iteration
    loop_state.transition(ReviewState.RETESTING)
    save_state(loop_state, base_dir)
    logger.info(
        "PR #%d: applied %d fixes, committed %s → retesting",
        loop_state.pr_number,
        summary.fixes_applied,
        summary.commit_sha or "nothing",
    )
    return loop_state


def _step_retesting(
    loop_state: ReviewLoopState,
    base_dir: Path | None,
) -> ReviewLoopState:
    """RETESTING → WAITING_FOR_CI: transition to CI polling after fixes pushed.

    Local `make check` was removed — the review loop runs in the main checkout,
    not the PR worktree, so local validation is unreliable.  The pushed commit
    triggers GitHub CI which validates on a clean checkout.
    """
    loop_state.ci_retry_count = 0
    loop_state.transition(ReviewState.WAITING_FOR_CI)
    save_state(loop_state, base_dir)
    logger.info(
        "PR #%d: retesting → waiting_for_ci (CI validates pushed fixes)",
        loop_state.pr_number,
    )
    return loop_state


def _step_ready_to_merge(
    loop_state: ReviewLoopState,
    base_dir: Path | None,
) -> ReviewLoopState:
    """READY_TO_MERGE → MERGED: Enable auto-merge and transition.

    Enables GitHub auto-merge (squash) on the PR. GitHub will merge
    once all branch protection requirements (CI, required statuses)
    are satisfied.
    """
    from github_pr_state import enable_auto_merge

    ok = enable_auto_merge(loop_state.pr_number)
    if ok:
        loop_state.transition(ReviewState.MERGED)
        save_state(loop_state, base_dir)
        logger.info(
            "PR #%d: auto-merge enabled → merged",
            loop_state.pr_number,
        )
    else:
        # Auto-merge not available (e.g., repo setting disabled, conflicts).
        # Stay at READY_TO_MERGE — human can merge manually.
        logger.warning(
            "PR #%d: auto-merge failed — manual merge required",
            loop_state.pr_number,
        )
        save_state(loop_state, base_dir)

    return loop_state


def main() -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description="Autonomous review loop driver")
    parser.add_argument("--pr", type=int, required=True, help="PR number")
    parser.add_argument(
        "--trigger",
        choices=["pr_created", "ci_complete", "manual"],
        default="manual",
        help="What triggered this invocation",
    )
    parser.add_argument(
        "--branch",
        default=None,
        help="Branch name (required for new loops)",
    )
    parser.add_argument(
        "--mode",
        choices=["standard", "report-audit", "plan-audit"],
        default=None,
        help="Review mode (auto-detected if not specified)",
    )
    parser.add_argument(
        "--max-iterations",
        type=int,
        default=3,
        help="Maximum review iterations (default: 3)",
    )
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(name)s %(levelname)s %(message)s",
    )

    # Get current HEAD SHA for idempotency tracking
    head_sha_result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        capture_output=True,
        text=True,
    )
    head_sha = (
        head_sha_result.stdout.strip() if head_sha_result.returncode == 0 else None
    )

    # Load or initialize state (with SHA-based staleness check)
    loop_state = load_state(args.pr, head_sha=head_sha)

    if loop_state is None:
        if args.branch is None:
            logger.error("--branch required for new review loops")
            return 1

        if args.mode:
            mode = ReviewMode(args.mode)
        else:
            # Auto-detect from PR's actual changed files (not local HEAD)
            try:
                from github_pr_state import get_pr_changed_files

                changed = get_pr_changed_files(args.pr)
                mode = classify_review_mode(changed)
            except Exception:
                logger.warning(
                    "PR #%d: failed to fetch PR files for mode detection — "
                    "falling back to git diff",
                    args.pr,
                )
                diff_result = subprocess.run(
                    ["git", "diff", "--name-only", "origin/main...HEAD"],
                    capture_output=True,
                    text=True,
                )
                if diff_result.returncode == 0:
                    changed = [
                        f.strip()
                        for f in diff_result.stdout.strip().split("\n")
                        if f.strip()
                    ]
                    mode = classify_review_mode(changed)
                else:
                    mode = ReviewMode.STANDARD
        loop_state = initialize_state(
            args.pr,
            args.branch,
            mode,
            args.max_iterations,
            head_sha=head_sha,
        )
        save_state(loop_state)
        logger.info(
            "PR #%d: new loop initialized (mode=%s, run_id=%s)",
            args.pr,
            mode.value,
            loop_state.run_id or "unknown",
        )

    # States where we should poll with a delay (waiting for external events)
    _POLLING_STATES = {ReviewState.WAITING_FOR_CI}

    # Loop until terminal state or timeout (15 minutes max)
    max_runtime_s = 900
    poll_interval_s = 30
    start_time = time.monotonic()

    while not loop_state.is_terminal:
        elapsed = time.monotonic() - start_time
        if elapsed > max_runtime_s:
            logger.warning(
                "PR #%d: runtime limit reached (%.0fs) — exiting. "
                "Rerun: python scripts/internal/review_driver.py "
                "--pr %d --trigger manual",
                loop_state.pr_number,
                elapsed,
                loop_state.pr_number,
            )
            break

        prev_state = loop_state.current_state

        try:
            loop_state = step(loop_state)
        except Exception as e:
            logger.exception("PR #%d: unhandled error", loop_state.pr_number)
            try:
                _publish_status(
                    loop_state.pr_number,
                    "failure",
                    (
                        f"Review crashed: {type(e).__name__}. "
                        f"Rerun: python scripts/internal/review_driver.py "
                        f"--pr {loop_state.pr_number} --trigger manual"
                    ),
                )
            except Exception:
                pass
            loop_state.stop_reason = f"Unhandled exception: {e}"
            try:
                loop_state.transition(ReviewState.STOPPED_REVIEW_FAILURE)
            except Exception:
                loop_state.state = ReviewState.STOPPED_REVIEW_FAILURE.value
            save_state(loop_state)
            _write_failure_sentinel(loop_state)
            return 1

        # If we didn't advance (stuck in a polling state), sleep before retry
        if loop_state.current_state == prev_state:
            if loop_state.current_state in _POLLING_STATES:
                logger.info(
                    "PR #%d: polling %s — sleeping %ds",
                    loop_state.pr_number,
                    loop_state.current_state.value,
                    poll_interval_s,
                )
                time.sleep(poll_interval_s)
            else:
                # Non-polling state that didn't advance — avoid tight loop
                time.sleep(5)

    # Report final state
    logger.info(
        "PR #%d: state=%s iteration=%d/%d",
        loop_state.pr_number,
        loop_state.current_state.value,
        loop_state.iteration_count,
        loop_state.max_iterations,
    )
    if loop_state.is_terminal:
        logger.info(
            "PR #%d: terminal -- reason: %s",
            loop_state.pr_number,
            loop_state.stop_reason or "completed",
        )
        _write_failure_sentinel(loop_state)

    return 0


if __name__ == "__main__":
    sys.exit(main())
