"""Review loop driver — main orchestrator for the autonomous review loop.

Runs as a background process launched by post-pr-review-loop.sh:
1. Loads state from disk (or initializes if new)
2. Loops: advance one step, sleep when polling, until terminal or timeout
3. Saves state and round artifacts after each step
4. Maximum runtime: 15 minutes

Idempotent: duplicate triggers are harmless (sentinel file in hook).
Entry point: python scripts/internal/review_driver.py --pr <N> --trigger <event>

Adapters:
- codex_review_adapter: Codex CLI invocation + output parsing
- claude_fix_adapter: deterministic fix application + commit
"""

from __future__ import annotations

import argparse
import json
import logging
import subprocess
import sys
import time
from pathlib import Path

from review_state import (
    TERMINAL_STATES,
    ReviewLoopState,
    ReviewMode,
    ReviewState,
    load_state,
    round_dir,
    save_state,
)

logger = logging.getLogger("review_driver")


def _publish_status(pr_number: int, state: str, description: str) -> bool:
    """Publish a review status to GitHub, logging errors but not raising.

    Args:
        pr_number: PR number.
        state: GitHub API state ("pending", "success", "failure").
        description: Short description (max 140 chars).

    Returns:
        True if published successfully, False otherwise.
    """
    try:
        from github_pr_state import publish_review_status

        ok = publish_review_status(pr_number, state, description[:140])
        if not ok:
            logger.warning("PR #%d: failed to publish status %s", pr_number, state)
        return ok
    except Exception:
        logger.exception("PR #%d: error publishing status %s", pr_number, state)
        return False


def _create_follow_up_issues(
    pr_number: int,
    findings: list[dict],
) -> list[str]:
    """Create GitHub issues for non-blocking findings (P2/WARN).

    Groups findings by category and creates one issue per category label.

    Args:
        pr_number: PR number the findings came from.
        findings: List of finding dicts with severity, category, etc.

    Returns:
        List of URLs for created issues.
    """
    warn_findings = [f for f in findings if f.get("severity") == "P2"]
    if not warn_findings:
        return []

    # Group by category -> label mapping
    _CATEGORY_LABEL_MAP = {
        "correctness": "fix:bug",
        "convention": "fix:convention",
        "test": "fix:test",
        "process": "fix:process",
        "provenance": "fix:docs",
    }

    by_label: dict[str, list[dict]] = {}
    for f in warn_findings:
        cat = f.get("category", "convention")
        label = _CATEGORY_LABEL_MAP.get(cat, "fix:convention")
        by_label.setdefault(label, []).append(f)

    issue_urls: list[str] = []
    for label, cat_findings in by_label.items():
        # Build issue body
        findings_table = (
            "| ID | File | Line | Description |\n|----|------|------|-------------|\n"
        )
        for f in cat_findings:
            findings_table += (
                f"| {f.get('check_id', '-')} "
                f"| {f.get('file', '-')} "
                f"| {f.get('line', '-')} "
                f"| {f.get('message', '-')} |\n"
            )

        body = (
            f"## Follow-up: PR #{pr_number}\n\n"
            "Findings from autonomous review loop that should be "
            "addressed post-merge.\n\n"
            f"### Findings\n{findings_table}\n"
            "---\n"
            f"*Auto-generated by review loop. Original PR: #{pr_number}*"
        )

        title = f"fix({label}): follow-up for PR #{pr_number}"

        # Try with labels first, fall back to without
        result = subprocess.run(
            [
                "gh",
                "issue",
                "create",
                "--title",
                title,
                "--label",
                f"{label},follow-up",
                "--body",
                body,
            ],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            # Retry without labels (they may not exist)
            result = subprocess.run(
                [
                    "gh",
                    "issue",
                    "create",
                    "--title",
                    title,
                    "--body",
                    body,
                ],
                capture_output=True,
                text=True,
            )

        if result.returncode == 0:
            url = result.stdout.strip()
            issue_urls.append(url)
            logger.info("Created follow-up issue: %s", url)
        else:
            logger.warning(
                "Failed to create follow-up issue for %s: %s",
                label,
                result.stderr[:200],
            )

    return issue_urls


def classify_review_mode(changed_files: list[str]) -> ReviewMode:
    """Determine review mode from the set of changed files.

    Most restrictive mode wins if mixed file types.
    """
    has_reports = any(f.startswith("docs/04_reports/") for f in changed_files)
    has_plans = any(f.startswith("plans/") for f in changed_files)

    if has_reports:
        return ReviewMode.REPORT_AUDIT
    if has_plans:
        return ReviewMode.PLAN_AUDIT
    return ReviewMode.STANDARD


def initialize_state(
    pr_number: int,
    branch: str,
    mode: ReviewMode,
    max_iterations: int = 5,
    *,
    head_sha: str | None = None,
) -> ReviewLoopState:
    """Create initial state for a new review loop.

    Args:
        pr_number: PR number.
        branch: Branch name.
        mode: Review mode.
        max_iterations: Maximum review iterations.
        head_sha: HEAD SHA at loop start (for idempotency tracking).
    """
    run_id = None
    if head_sha:
        run_id = f"pr_{pr_number}_{head_sha[:7]}"
    return ReviewLoopState(
        pr_number=pr_number,
        branch=branch,
        mode=mode.value,
        state=ReviewState.INITIALIZED.value,
        max_iterations=max_iterations,
        initial_head_sha=head_sha,
        current_head_sha=head_sha,
        run_id=run_id,
    )


def step(
    loop_state: ReviewLoopState,
    *,
    base_dir: Path | None = None,
) -> ReviewLoopState:
    """Advance the state machine by one step.

    This is the main dispatch function. Each call makes bounded progress
    (one transition) and returns the updated state.

    Args:
        loop_state: Current state.
        base_dir: Override for state persistence directory.

    Returns:
        Updated state (also persisted to disk).
    """
    current = loop_state.current_state

    # Terminal states → no-op
    if current in TERMINAL_STATES:
        logger.info(
            "PR #%d: terminal state %s — no-op",
            loop_state.pr_number,
            current.value,
        )
        return loop_state

    # Check max iterations (global stop condition)
    if loop_state.iteration_count >= loop_state.max_iterations:
        _publish_status(
            loop_state.pr_number,
            "failure",
            f"Review stopped -- max iterations ({loop_state.max_iterations})",
        )
        loop_state.transition(ReviewState.STOPPED_MAX_ITERATIONS)
        loop_state.stop_reason = f"Hit max iterations ({loop_state.max_iterations})"
        save_state(loop_state, base_dir)
        logger.warning(
            "PR #%d: stopped -- max iterations (%d)",
            loop_state.pr_number,
            loop_state.max_iterations,
        )
        return loop_state

    # Dispatch by current state
    if current == ReviewState.INITIALIZED:
        return _step_initialized(loop_state, base_dir)
    elif current == ReviewState.PR_OPEN:
        return _step_pr_open(loop_state, base_dir)
    elif current == ReviewState.WAITING_FOR_CI:
        return _step_waiting_for_ci(loop_state, base_dir)
    elif current == ReviewState.WAITING_FOR_CODEX:
        return _step_waiting_for_codex(loop_state, base_dir)
    elif current == ReviewState.APPLYING_FIXES:
        return _step_applying_fixes(loop_state, base_dir)
    elif current == ReviewState.RETESTING:
        return _step_retesting(loop_state, base_dir)
    elif current == ReviewState.READY_TO_MERGE:
        return _step_ready_to_merge(loop_state, base_dir)
    else:
        logger.error(
            "PR #%d: unexpected state %s",
            loop_state.pr_number,
            current.value,
        )
        return loop_state


def _step_initialized(
    loop_state: ReviewLoopState,
    base_dir: Path | None,
) -> ReviewLoopState:
    """INITIALIZED → PR_OPEN: PR exists, transition to open."""
    _publish_status(loop_state.pr_number, "pending", "Review loop started")
    loop_state.transition(ReviewState.PR_OPEN)
    save_state(loop_state, base_dir)
    logger.info("PR #%d: initialized → pr_open", loop_state.pr_number)
    return loop_state


def _step_pr_open(
    loop_state: ReviewLoopState,
    base_dir: Path | None,
) -> ReviewLoopState:
    """PR_OPEN → WAITING_FOR_CI: Run prechecks + make check, then wait for CI."""
    from deterministic_prechecks import check_diff, get_blocking_findings

    # 1. Run deterministic prechecks
    findings = check_diff(mode=loop_state.mode)
    blocking = get_blocking_findings(findings)

    # Save precheck results for this round
    rdir = round_dir(loop_state.pr_number, loop_state.iteration_count + 1, base_dir)
    rdir.mkdir(parents=True, exist_ok=True)
    with open(rdir / "prechecks.json", "w") as f:
        json.dump([f.to_dict() for f in findings], f, indent=2)

    if blocking:
        # Blocking prechecks -> stop (these are deterministic, unfixable by Codex)
        _publish_status(
            loop_state.pr_number,
            "failure",
            f"Blocking prechecks: {len(blocking)} findings",
        )
        loop_state.transition(ReviewState.STOPPED_CI_FAILURE)
        loop_state.stop_reason = (
            f"Blocking deterministic precheck failures: {len(blocking)} findings"
        )
        save_state(loop_state, base_dir)
        logger.warning(
            "PR #%d: blocking prechecks (%d findings) -- stopped",
            loop_state.pr_number,
            len(blocking),
        )
        return loop_state

    # 2. Run make check (initial validation before CI)
    from claude_fix_adapter import run_make_check

    if not run_make_check():
        _publish_status(loop_state.pr_number, "failure", "make check failed")
        loop_state.transition(ReviewState.STOPPED_CI_FAILURE)
        loop_state.stop_reason = "make check failed in initial validation"
        save_state(loop_state, base_dir)
        logger.warning(
            "PR #%d: make check failed -- stopped",
            loop_state.pr_number,
        )
        return loop_state

    # 3. Prechecks + make check passed -> wait for CI (remote)
    loop_state.transition(ReviewState.WAITING_FOR_CI)
    save_state(loop_state, base_dir)
    logger.info("PR #%d: pr_open -> waiting_for_ci", loop_state.pr_number)
    return loop_state


def _step_waiting_for_ci(
    loop_state: ReviewLoopState,
    base_dir: Path | None,
) -> ReviewLoopState:
    """WAITING_FOR_CI → WAITING_FOR_CODEX or STOPPED_CI_FAILURE."""
    from github_pr_state import get_ci_status

    ci_status = get_ci_status(loop_state.pr_number)
    loop_state.last_ci_status = ci_status

    if ci_status == "pending":
        # Not ready yet — save state and exit (resume on next trigger)
        save_state(loop_state, base_dir)
        logger.info("PR #%d: CI pending — will resume", loop_state.pr_number)
        return loop_state

    if ci_status == "failure":
        _publish_status(loop_state.pr_number, "failure", "CI failed")
        loop_state.transition(ReviewState.STOPPED_CI_FAILURE)
        loop_state.stop_reason = "CI failed"
        save_state(loop_state, base_dir)
        logger.warning("PR #%d: CI failed -- stopped", loop_state.pr_number)
        return loop_state

    if ci_status == "success":
        loop_state.transition(ReviewState.WAITING_FOR_CODEX)
        save_state(loop_state, base_dir)
        logger.info(
            "PR #%d: waiting_for_ci → waiting_for_codex",
            loop_state.pr_number,
        )
        return loop_state

    # Unknown CI status — treat as pending
    save_state(loop_state, base_dir)
    logger.info(
        "PR #%d: CI status unknown (%s) — will resume",
        loop_state.pr_number,
        ci_status,
    )
    return loop_state


def _step_waiting_for_codex(
    loop_state: ReviewLoopState,
    base_dir: Path | None,
) -> ReviewLoopState:
    """WAITING_FOR_CODEX → APPLYING_FIXES or READY_TO_MERGE.

    Invokes Codex CLI, parses findings, and decides next transition:
    - Blocking findings → APPLYING_FIXES
    - No blocking findings → READY_TO_MERGE
    - Invocation failure → retry or STOPPED_REVIEW_FAILURE
    """
    from codex_review_adapter import (
        get_blocking_findings,
        invoke_codex_cli,
        save_review_result,
    )
    from review_state import compute_findings_hash

    iteration = loop_state.iteration_count + 1

    _publish_status(
        loop_state.pr_number,
        "pending",
        f"Codex CLI review in progress (round {iteration})",
    )

    result = invoke_codex_cli(mode=loop_state.mode)
    save_review_result(result, loop_state.pr_number, iteration, base_dir)

    if not result.success:
        loop_state.codex_retry_count += 1
        if loop_state.codex_retry_count >= 3:
            _publish_status(
                loop_state.pr_number,
                "failure",
                f"Codex CLI failed {loop_state.codex_retry_count} times",
            )
            loop_state.transition(ReviewState.STOPPED_REVIEW_FAILURE)
            loop_state.last_codex_status = "failed"
            loop_state.stop_reason = (
                f"Codex CLI failed {loop_state.codex_retry_count} times: {result.error}"
            )
            save_state(loop_state, base_dir)
            logger.warning(
                "PR #%d: Codex CLI failed %d times -- stopped",
                loop_state.pr_number,
                loop_state.codex_retry_count,
            )
        else:
            loop_state.last_codex_status = "retry"
            save_state(loop_state, base_dir)
            logger.info(
                "PR #%d: Codex CLI failed (attempt %d/%d) — will retry",
                loop_state.pr_number,
                loop_state.codex_retry_count,
                3,
            )
        return loop_state

    # Reset retry count on success
    loop_state.codex_retry_count = 0
    loop_state.last_codex_status = "success"

    blocking = get_blocking_findings(result.findings)

    if not blocking:
        # Create follow-up issues for P2 findings before transitioning
        all_findings_dicts = [f.to_dict() for f in result.findings]
        p2_count = sum(1 for f in all_findings_dicts if f.get("severity") == "P2")
        follow_up_urls = _create_follow_up_issues(
            loop_state.pr_number, all_findings_dicts
        )

        # Publish success status with finding summary
        if p2_count > 0:
            desc = (
                f"Review passed -- {p2_count} warnings "
                f"({len(follow_up_urls)} follow-up issues created)"
            )
        else:
            desc = "Review passed -- clean"
        _publish_status(loop_state.pr_number, "success", desc)

        loop_state.transition(ReviewState.READY_TO_MERGE)
        save_state(loop_state, base_dir)
        logger.info(
            "PR #%d: no blocking Codex findings -> ready_to_merge",
            loop_state.pr_number,
        )
        return loop_state

    # Check for stagnation before advancing to fix round
    findings_dicts = [f.to_dict() for f in result.findings]
    current_hash = compute_findings_hash(findings_dicts)

    if current_hash == loop_state.last_findings_hash:
        _publish_status(
            loop_state.pr_number,
            "failure",
            "Review stopped -- no progress after fixes",
        )
        loop_state.transition(ReviewState.STOPPED_NO_PROGRESS)
        loop_state.stop_reason = (
            f"Same findings hash ({current_hash}) -- no progress after fixes"
        )
        save_state(loop_state, base_dir)
        logger.warning(
            "PR #%d: stagnation detected (hash=%s) -- stopped",
            loop_state.pr_number,
            current_hash,
        )
        return loop_state

    loop_state.last_findings_hash = current_hash
    loop_state.transition(ReviewState.APPLYING_FIXES)
    save_state(loop_state, base_dir)
    logger.info(
        "PR #%d: %d blocking Codex findings → applying_fixes",
        loop_state.pr_number,
        len(blocking),
    )
    return loop_state


def _step_applying_fixes(
    loop_state: ReviewLoopState,
    base_dir: Path | None,
) -> ReviewLoopState:
    """APPLYING_FIXES → RETESTING.

    Loads the latest Codex findings, applies auto-fixable patterns,
    commits, and pushes. Transitions to RETESTING on success.
    """
    from claude_fix_adapter import (
        apply_fixes,
        commit_fixes,
        push_fixes,
        save_fix_summary,
    )

    iteration = loop_state.iteration_count + 1

    # Load findings from this round's Codex review
    rdir = round_dir(loop_state.pr_number, iteration, base_dir)
    codex_path = rdir / "codex_review.json"

    if codex_path.exists():
        with open(codex_path) as f:
            review_data = json.load(f)
        findings = review_data.get("findings", [])
    else:
        logger.warning(
            "PR #%d: no codex_review.json found for round %d",
            loop_state.pr_number,
            iteration,
        )
        findings = []

    # Apply auto-fixable patterns
    summary = apply_fixes(findings)
    save_fix_summary(summary, loop_state.pr_number, iteration, base_dir)

    if summary.fixes_applied == 0:
        # No auto-fixes possible — still transition to RETESTING
        # (manual fixes may have been applied externally)
        logger.info(
            "PR #%d: no auto-fixes applied (%d skipped) — retesting anyway",
            loop_state.pr_number,
            summary.fixes_skipped,
        )
        loop_state.iteration_count = iteration
        loop_state.transition(ReviewState.RETESTING)
        save_state(loop_state, base_dir)
        return loop_state

    # Commit and push
    commit_fixes(summary, loop_state.pr_number, iteration)
    if summary.commit_sha:
        push_fixes(loop_state.branch)
        loop_state.last_head_sha = summary.commit_sha
        loop_state.current_head_sha = summary.commit_sha

    loop_state.iteration_count = iteration
    loop_state.transition(ReviewState.RETESTING)
    save_state(loop_state, base_dir)
    logger.info(
        "PR #%d: applied %d fixes, committed %s → retesting",
        loop_state.pr_number,
        summary.fixes_applied,
        summary.commit_sha or "nothing",
    )
    return loop_state


def _step_retesting(
    loop_state: ReviewLoopState,
    base_dir: Path | None,
) -> ReviewLoopState:
    """RETESTING → WAITING_FOR_CI or STOPPED_CI_FAILURE.

    Runs make check locally. On success, transitions to WAITING_FOR_CI
    (CI will re-run on the pushed commit). On failure after 3 retries,
    stops with STOPPED_CI_FAILURE.
    """
    from claude_fix_adapter import run_make_check

    if run_make_check():
        loop_state.ci_retry_count = 0
        loop_state.transition(ReviewState.WAITING_FOR_CI)
        save_state(loop_state, base_dir)
        logger.info("PR #%d: make check passed → waiting_for_ci", loop_state.pr_number)
        return loop_state

    loop_state.ci_retry_count += 1
    if loop_state.ci_retry_count >= 3:
        _publish_status(
            loop_state.pr_number,
            "failure",
            f"make check failed {loop_state.ci_retry_count} times",
        )
        loop_state.transition(ReviewState.STOPPED_CI_FAILURE)
        loop_state.stop_reason = f"make check failed {loop_state.ci_retry_count} times"
        save_state(loop_state, base_dir)
        logger.warning(
            "PR #%d: make check failed %d times -- stopped",
            loop_state.pr_number,
            loop_state.ci_retry_count,
        )
    else:
        save_state(loop_state, base_dir)
        logger.info(
            "PR #%d: make check failed (attempt %d/3) — will retry",
            loop_state.pr_number,
            loop_state.ci_retry_count,
        )
    return loop_state


def _step_ready_to_merge(
    loop_state: ReviewLoopState,
    base_dir: Path | None,
) -> ReviewLoopState:
    """READY_TO_MERGE → MERGED: Enable auto-merge and transition.

    Enables GitHub auto-merge (squash) on the PR. GitHub will merge
    once all branch protection requirements (CI, required statuses)
    are satisfied.
    """
    from github_pr_state import enable_auto_merge

    ok = enable_auto_merge(loop_state.pr_number)
    if ok:
        loop_state.transition(ReviewState.MERGED)
        save_state(loop_state, base_dir)
        logger.info(
            "PR #%d: auto-merge enabled → merged",
            loop_state.pr_number,
        )
    else:
        # Auto-merge not available (e.g., repo setting disabled, conflicts).
        # Stay at READY_TO_MERGE — human can merge manually.
        logger.warning(
            "PR #%d: auto-merge failed — manual merge required",
            loop_state.pr_number,
        )
        save_state(loop_state, base_dir)

    return loop_state


def main() -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description="Autonomous review loop driver")
    parser.add_argument("--pr", type=int, required=True, help="PR number")
    parser.add_argument(
        "--trigger",
        choices=["pr_created", "ci_complete", "manual"],
        default="manual",
        help="What triggered this invocation",
    )
    parser.add_argument(
        "--branch",
        default=None,
        help="Branch name (required for new loops)",
    )
    parser.add_argument(
        "--mode",
        choices=["standard", "report-audit", "plan-audit"],
        default=None,
        help="Review mode (auto-detected if not specified)",
    )
    parser.add_argument(
        "--max-iterations",
        type=int,
        default=5,
        help="Maximum review iterations (default: 5)",
    )
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(name)s %(levelname)s %(message)s",
    )

    # Get current HEAD SHA for idempotency tracking
    head_sha_result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        capture_output=True,
        text=True,
    )
    head_sha = (
        head_sha_result.stdout.strip() if head_sha_result.returncode == 0 else None
    )

    # Load or initialize state (with SHA-based staleness check)
    loop_state = load_state(args.pr, head_sha=head_sha)

    if loop_state is None:
        if args.branch is None:
            logger.error("--branch required for new review loops")
            return 1

        if args.mode:
            mode = ReviewMode(args.mode)
        else:
            # Auto-detect from changed files
            diff_result = subprocess.run(
                ["git", "diff", "--name-only", "origin/main...HEAD"],
                capture_output=True,
                text=True,
            )
            if diff_result.returncode == 0:
                changed = [
                    f.strip()
                    for f in diff_result.stdout.strip().split("\n")
                    if f.strip()
                ]
                mode = classify_review_mode(changed)
            else:
                mode = ReviewMode.STANDARD
        loop_state = initialize_state(
            args.pr,
            args.branch,
            mode,
            args.max_iterations,
            head_sha=head_sha,
        )
        save_state(loop_state)
        logger.info(
            "PR #%d: new loop initialized (mode=%s, run_id=%s)",
            args.pr,
            mode.value,
            loop_state.run_id or "unknown",
        )

    # States where we should poll with a delay (waiting for external events)
    _POLLING_STATES = {ReviewState.WAITING_FOR_CI}

    # Loop until terminal state or timeout (15 minutes max)
    max_runtime_s = 900
    poll_interval_s = 30
    start_time = time.monotonic()

    while not loop_state.is_terminal:
        elapsed = time.monotonic() - start_time
        if elapsed > max_runtime_s:
            logger.warning(
                "PR #%d: runtime limit reached (%.0fs) — exiting. "
                "Rerun: python scripts/internal/review_driver.py "
                "--pr %d --trigger manual",
                loop_state.pr_number,
                elapsed,
                loop_state.pr_number,
            )
            break

        prev_state = loop_state.current_state

        try:
            loop_state = step(loop_state)
        except Exception as e:
            logger.exception("PR #%d: unhandled error", loop_state.pr_number)
            try:
                _publish_status(
                    loop_state.pr_number,
                    "failure",
                    (
                        f"Review crashed: {type(e).__name__}. "
                        f"Rerun: python scripts/internal/review_driver.py "
                        f"--pr {loop_state.pr_number} --trigger manual"
                    ),
                )
            except Exception:
                pass
            loop_state.stop_reason = f"Unhandled exception: {e}"
            try:
                loop_state.transition(ReviewState.STOPPED_REVIEW_FAILURE)
            except Exception:
                loop_state.state = ReviewState.STOPPED_REVIEW_FAILURE.value
            save_state(loop_state)
            return 1

        # If we didn't advance (stuck in a polling state), sleep before retry
        if loop_state.current_state == prev_state:
            if loop_state.current_state in _POLLING_STATES:
                logger.info(
                    "PR #%d: polling %s — sleeping %ds",
                    loop_state.pr_number,
                    loop_state.current_state.value,
                    poll_interval_s,
                )
                time.sleep(poll_interval_s)
            else:
                # Non-polling state that didn't advance — avoid tight loop
                time.sleep(5)

    # Report final state
    logger.info(
        "PR #%d: state=%s iteration=%d/%d",
        loop_state.pr_number,
        loop_state.current_state.value,
        loop_state.iteration_count,
        loop_state.max_iterations,
    )
    if loop_state.is_terminal:
        logger.info(
            "PR #%d: terminal -- reason: %s",
            loop_state.pr_number,
            loop_state.stop_reason or "completed",
        )

    return 0


if __name__ == "__main__":
    sys.exit(main())
